# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/sysutils/rubygem-log4r/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	log4r
PORTVERSION=	1.1.10
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Flexible logging library for use in Ruby programs

LICENSE=	LGPL3

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
