# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/misc/R-cran-mime/Makefile 393712 2015-08-08 06:01:28Z tota $

PORTNAME=	mime
PORTVERSION=	0.3
CATEGORIES=	misc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Map Filenames to MIME Types

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
