# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/www/pear-Services_Yahoo/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_Yahoo
PORTVERSION=	0.2.0
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Provides access to the Yahoo! Web Services

USES=	pear

.include <bsd.port.mk>
