# Created by: Michael Frey <frey@raum3.de>
# $FreeBSD: head/net/pear-Net_IDNA/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_IDNA
PORTVERSION=	0.8.1
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Pear Punycode encoding and decoding package

USES=	pear

.include <bsd.port.mk>
