# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD: head/www/rubygem-rqrcode-rails3/Makefile 393823 2015-08-09 20:10:35Z swills $

PORTNAME=	rqrcode-rails3
PORTVERSION=	0.1.7
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Render QR codes with Rails 3

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rqrcode>=0.4.2:${PORTSDIR}/www/rubygem-rqrcode

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
