# Created by: Qian Jin <eric.siroh@gmail.com>
# $FreeBSD: head/finance/py-vatnumber/Makefile 390156 2015-06-20 09:39:48Z wen $

PORTNAME=	vatnumber
PORTVERSION=	1.2
CATEGORIES=	finance python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	chian.jin@gmail.com
COMMENT=	Python module to validate VAT numbers

LICENSE=	GPLv3

# Python3 ready
USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
