# $FreeBSD: head/devel/elixir-bson/Makefile 391561 2015-07-08 11:36:34Z vanilla $

PORTNAME=	elixir-bson
PORTVERSION=	0.4.3
CATEGORIES=	devel

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	BSON implementation in Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	checkiz

ELIXIR_APP_NAME=bson

.include <bsd.port.mk>
