# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/sysutils/p5-Proc-PidUtil/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Proc-PidUtil
PORTVERSION=	0.09
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	PID file management utilities

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
