# Created by: Wen heping <wenheping@gmail.com>)
# $FreeBSD: head/www/pear-Services_Google/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_Google
PORTVERSION=	0.2.0
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP interface to access the Google SOAP Web APIs

USES=	pear
USE_PHP=	soap

.include <bsd.port.mk>
