# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/devel/pear-XML_Parser/Makefile 394854 2015-08-20 11:36:50Z bofh $

PORTNAME=	XML_Parser
PORTVERSION=	1.3.5
CATEGORIES=	devel pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR XML parsing class based on PHP's bundled expat

LICENSE=	BSD2CLAUSE

USES=		pear

.include <bsd.port.mk>
