# $FreeBSD: head/sysutils/rcm/Makefile 372360 2014-11-09 12:05:46Z marino $

PORTNAME=	rcm
PORTVERSION=	1.2.3
CATEGORIES=	sysutils
MASTER_SITES=	https://thoughtbot.github.io/rcm/dist/

MAINTAINER=	leonardo@schenkel.net
COMMENT=	RC file (dotfile) management

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
