# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/www/drupal6-mimedetect/Makefile 364158 2014-08-06 09:11:57Z olgeni $

PORTNAME=	mimedetect
DISTVERSION=	6.x-1.3
CATEGORIES=	www
MASTER_SITES=	http://ftp.drupal.org/files/projects/

MAINTAINER=	wenheping@gmail.com
COMMENT=	API for Consistent Server Side Mime Detection

USES=		drupal:6,module

MODULE_FILES=	magic magic.mgc magic.mime \
		mimedetect.info mimedetect.install mimedetect.module
DOC_FILES=	LICENSE.txt README.txt

.include <bsd.port.mk>
