# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-odfpy/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	odfpy
PORTVERSION=	0.9.6
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP \
		http://opendocumentfellowship.com/files/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Python API and Tools to Manipulate OpenDocument Files

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
