# Created by: Vladimir Chukharev
# $FreeBSD: head/devel/py-robotframework/Makefile 393603 2015-08-05 18:44:07Z robak $

PORTNAME=	robotframework
PORTVERSION=	2.9
CATEGORIES=	devel www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	Vladimir.Chukharev@gmail.com
COMMENT=	Generic test automation framework

LICENSE=	APACHE20

USES=		python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
