# $FreeBSD: head/security/elixir-comeonin/Makefile 393065 2015-07-28 10:43:20Z olgeni $

PORTNAME=	comeonin
PORTVERSION=	1.1.0
DISTVERSIONPREFIX=	v
CATEGORIES=	security
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Password hashing library for Elixir

LICENSE=	BSD3CLAUSE BSD4CLAUSE
LICENSE_COMB=	multi

USES=		elixir gmake
USE_GITHUB=	yes
GH_ACCOUNT=	elixircnx

.include <bsd.port.mk>
