# Created by: clsung
# $FreeBSD: head/textproc/p5-Text-Affixes/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Affixes
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for prefixes and suffixes analisys of text

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
