# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/textproc/pear-Horde_Xml_Element/Makefile 385085 2015-05-01 07:11:54Z mm $

PORTNAME=	Horde_Xml_Element
PORTVERSION=	2.0.3
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Xml Element object

USES=	horde
USE_PHP=	dom
USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.mk>
