# $FreeBSD: head/devel/elixir-estree/Makefile 394607 2015-08-18 15:41:06Z olgeni $

PORTNAME=	elixir-estree
PORTVERSION=	2.0.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	JavaScript AST to JavaScript code generator in Elixir 

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	bryanjos

ELIXIR_APP_NAME=estree

.include <bsd.port.mk>
