# $FreeBSD: head/hungarian/libreoffice/Makefile 371023 2014-10-16 21:14:18Z jkim $

LO_I18N=	hu
LO_HAS_HELPPACK=	yes
CATEGORIES=	hungarian editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
