# Created by: Sheldon Hearn <sheldonh@FreeBSD.org>
# $FreeBSD: head/devel/p5-Config-General/Makefile 388434 2015-06-03 14:54:02Z jadawin $

PORTNAME=	Config-General
PORTVERSION=	2.58
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Perl5 module for handling Apache-style configuration files

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
