# $FreeBSD: head/devel/pear-Date_Holidays_USA/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Date_Holidays_USA
PORTVERSION=	0.1.1
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Driver based class to calculate holidays in the USA

BUILD_DEPENDS=	${PEARDIR}/Date/Holidays.php:${PORTSDIR}/devel/pear-Date_Holidays
BUILD_DEPENDS=	${PEARDIR}/Date/Holidays.php:${PORTSDIR}/devel/pear-Date_Holidays

USES=	pear

.include <bsd.port.mk>
