# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: head/textproc/rubygem-ini/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	ini
PORTVERSION=	0.1.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby INI File Parser and Writer

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
