# Created by: William Grzybowski <william88@gmail.com>
# $FreeBSD: head/devel/py-mccabe/Makefile 370456 2014-10-08 16:46:24Z wg $

PORTNAME=	mccabe
PORTVERSION=	0.2.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Ned's script to check McCabe complexity

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
