# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/www/py-django-classy-tags/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	django-classy-tags
PORTVERSION=	0.5.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Class based template tags for Django

RUN_DEPENDS=	${PYTHON_SITELIBDIR}/django/bin/django-admin.py:${PORTSDIR}/www/py-django

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
