# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD: head/security/rubygem-encryptor/Makefile 393824 2015-08-09 20:17:48Z swills $

PORTNAME=	encryptor
PORTVERSION=	1.3.0
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Wrapper for the standard ruby OpenSSL library

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes

.include <bsd.port.mk>
