# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/science/libquantum/Makefile 361238 2014-07-08 13:34:32Z tijl $

PORTNAME=	libquantum
PORTVERSION=	1.1.0
PORTREVISION=	1
CATEGORIES=	science
MASTER_SITES=	http://www.libquantum.de/files/

MAINTAINER=	wenheping@gmail.com
COMMENT=	C library for quantum computing and quantum simulation

GNU_CONFIGURE=	yes
USES=		gmake libtool
USE_LDCONFIG=	yes

.include <bsd.port.mk>
