# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/databases/pear-DB/Makefile 386097 2015-05-11 18:34:57Z mat $

PORTNAME=	DB
PORTVERSION=	1.7.14
PORTEPOCH=	1
CATEGORIES=	databases www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR Database Abstraction Layer

USES=		pear

.include <bsd.port.mk>
