# $FreeBSD: head/www/py-plone.synchronize/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	plone.synchronize
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Simple decorators to support synchronized methods

LICENSE=	BSD3CLAUSE

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
