# Created by: Rui Lopes (rgl ruilopes com)
# $FreeBSD: head/devel/rubygem-tzinfo/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	tzinfo
PORTVERSION=	1.2.2
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Daylight-savings aware timezone support for Ruby

LICENSE=	MIT

RUN_DEPENDS=	rubygem-thread_safe1>=0.1:${PORTSDIR}/devel/rubygem-thread_safe1

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
