# Created by: Anish Mistry (<amistry@am-productions.biz>)
# $FreeBSD: head/devel/pear-Validate_Finance_CreditCard/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Validate_Finance_CreditCard
PORTVERSION=	0.5.3
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR CreditCard Validation class

USES=	pear

.include <bsd.port.mk>
