# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/net/pear-Net_Traceroute/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_Traceroute
PORTVERSION=	0.21.3
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class to execute traceroute

USES=	pear

.include <bsd.port.mk>
