# $FreeBSD: head/net/rubygem-connection_pool/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	connection_pool
PORTVERSION=	2.2.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Generic connection pool for Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
