# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: head/devel/rubygem-rb-fsevent/Makefile 387202 2015-05-24 00:05:01Z sunpoet $

PORTNAME=	rb-fsevent
PORTVERSION=	0.9.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	FSEvents API with Signals catching (without RubyCocoa)

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
