# Created by: Boris Samorodov <bsam@FreeBSD.org>
# $FreeBSD: head/french/eric4/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTREVISION=	1
CATEGORIES=	french devel python

I18N_LANG=	fr

.include "${.CURDIR}/../../devel/eric4/Makefile.inc"
