# $FreeBSD: head/sysutils/cfengine/Makefile 392964 2015-07-27 06:39:28Z cy $

VERSIONS=		22 32 33 34 35 36 37
CFENGINE_VERSION?=	36

MASTERDIR=		${.CURDIR}/../cfengine${CFENGINE_VERSION}

.include "${MASTERDIR}/Makefile"
