# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php55-pdo_firebird/Makefile 343492 2014-02-09 12:46:09Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-pdo_firebird

.include "${MASTERDIR}/Makefile"
