# Created by: joerg
# $FreeBSD: head/editors/bpatch/Makefile 383385 2015-04-05 22:20:35Z bapt $

PORTNAME=	bpatch
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	editors
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/
DISTNAME=	${PORTNAME}

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	Hex editor that doesn't load the whole file at once

BROKEN=		Unfetchable
NO_WRKSUBDIR=   yes
PLIST_FILES=	bin/bpatch \
		man/man1/bpatch.1.gz

.include <bsd.port.mk>
