# Created by: Phil Maker <pjm@gnu.org>
# $FreeBSD: head/devel/nana/Makefile 354997 2014-05-24 07:37:07Z vanilla $

PORTNAME=	nana
PORTVERSION=	2.5
CATEGORIES=	devel
MASTER_SITES=	http://download.savannah.gnu.org/releases/nana/ \
		ftp://download.savannah.gnu.org/releases/nana/ 

MAINTAINER=	pjm@gnu.org
COMMENT=	Support for assertion checking and logging using GNU C and GDB

GNU_CONFIGURE=	yes

INFO=		nana

.include <bsd.port.mk>
