# $FreeBSD: head/graphics/graphos/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	graphos
PORTVERSION=	0.5
PORTREVISION=	2
CATEGORIES=	graphics gnustep
MASTER_SITES=	SAVANNAH/gap
DISTNAME=	Graphos-${PORTVERSION}

MAINTAINER=	theraven@FreeBSD.org
COMMENT=	Vector drawing application centered around bezier paths

LICENSE=	GPLv2

USES=		gnustep
USE_GNUSTEP=	back build
USE_LDCONFIG=	${GNUSTEP_LOCAL_LIBRARIES}

.include <bsd.port.mk>
