# $FreeBSD: head/editors/calligra-l10n-en_GB/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	calligra-l10n
PORTVERSION=	2.6.4
PORTREVISION=	3
CATEGORIES=	editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	British messages and documentation for Calligra

CALLIGRA_L10N=	en_GB

USES=	tar:bzip2

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
