# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/devel/p5-AtExit/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	AtExit
PORTVERSION=	2.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perform exit processing for a program or object

LICENSE=	ART10

TEST_DEPENDS=	p5-Capture-Tiny>0:${PORTSDIR}/devel/p5-Capture-Tiny

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
