# $FreeBSD: head/textproc/rubygem-rails-html-sanitizer/Makefile 389404 2015-06-13 13:54:59Z sunpoet $

PORTNAME=	rails-html-sanitizer
PORTVERSION=	1.0.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sanitize HTML fragments in Rails applications

LICENSE=	MIT

RUN_DEPENDS=	rubygem-loofah>=2.0:${PORTSDIR}/textproc/rubygem-loofah

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
