# $FreeBSD: head/games/fortunate/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	fortunate
PORTVERSION=	3.1
PORTREVISION=	4
CATEGORIES=	games gnustep
MASTER_SITES=	GNUSTEP_CH

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Graphical front-end to the command-line BSD fortune

USES=		gnustep
USE_GNUSTEP=	back build

.include <bsd.port.mk>
