# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/chinese/p5-Lingua-ZH-BPMFConvert/Makefile 383351 2015-04-05 18:38:33Z bapt $

PORTNAME=	Lingua-ZH-BPMFConvert
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	chinese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Rule-based conversion of BPMF (bopomofo) into Hanyu Pinyin

BROKEN=		Unfetchable
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
