# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/sysutils/p5-Unix-Processors/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Unix-Processors
PORTVERSION=	2.043
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Interface to processor (CPU) information

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
