# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/devel/py-mox/Makefile 373790 2014-12-02 22:40:56Z bapt $

PORTNAME=	mox
PORTVERSION=	0.5.3
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Mock object framework for Python

PROJECTHOST=	pymox
USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
