# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@sunpoet.net>
# $FreeBSD: head/databases/p5-PostgreSQL-PLPerl-Call/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	PostgreSQL-PLPerl-Call
PORTVERSION=	1.006
PORTREVISION=	1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:TIMB
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simple interface for calling SQL functions from PostgreSQL PL/Perl

BUILD_DEPENDS=	p5-DBI>=1.60.5:${PORTSDIR}/databases/p5-DBI

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
