# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/devel/py-babelfish/Makefile 390430 2015-06-23 16:37:42Z wg $

PORTNAME=	babelfish
PORTVERSION=	0.5.4
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Module to work with countries and languages

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
