# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/p5-experimental/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	experimental
PORTVERSION=	0.013
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:LEONT
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Experimental features made easy

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	modbuildtiny
USES=		perl5

.include <bsd.port.mk>
