# Created by: Daniel Baker <dbaker@FreeBSD.org>
# $FreeBSD: head/astro/dgpsip/Makefile 383279 2015-04-05 09:55:54Z bapt $

PORTNAME=	dgpsip
PORTVERSION=	1.35
CATEGORIES=	astro geography
MASTER_SITES=	http://www.madbavarian.org/ftp/

MAINTAINER=	jharris@widomaker.com
COMMENT=	Differential GPS over IP communication device

BROKEN=		No public distfiles

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/dgpsip \
		man/man1/dgpsip.1.gz

.include <bsd.port.mk>
