# Created by: Michael Moll <kvedulv@kvedulv.de>
# $FreeBSD: head/sysutils/rubygem-chef-api/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	chef-api
PORTVERSION=	0.5.0
CATEGORIES=	sysutils ruby
MASTER_SITES=	RG

MAINTAINER=	mmoll@FreeBSD.org
COMMENT=	Leightweight Chef API client

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-logify>=0.1:${PORTSDIR}/sysutils/rubygem-logify

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
