# Created by: Nakata Maho <chat95@mbox.kyoto-inet.or.jp>
# $FreeBSD: head/science/mpqc-mpich/Makefile 367610 2014-09-08 00:20:03Z marino $

MASTERDIR=	${.CURDIR}/../mpqc

PKGNAMESUFFIX=	-mpich

WITH_MPICH=	yes

.include "${MASTERDIR}/Makefile"
