# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/devel/p5-Proc-Wait3/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Proc-Wait3
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl extension for wait3 system call

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
