# Created by: chinsan
# $FreeBSD: head/net/pear-Net_Geo/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_Geo
PORTVERSION=	1.0.5
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Geographical locations based on Internet address

BUILD_DEPENDS=	${PEARDIR}/Cache.php:${PORTSDIR}/sysutils/pear-Cache \
		${PEARDIR}/XML/Serializer.php:${PORTSDIR}/devel/pear-XML_Serializer
RUN_DEPENDS=	${PEARDIR}/Cache.php:${PORTSDIR}/sysutils/pear-Cache \
		${PEARDIR}/XML/Serializer.php:${PORTSDIR}/devel/pear-XML_Serializer

USES=	pear

.include <bsd.port.mk>
