# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py-python2-pythondialog/Makefile 389619 2015-06-14 09:25:14Z sunpoet $

PORTNAME=	python2-pythondialog
PORTVERSION=	3.3.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Backport of pythondialog to Python 2

LICENSE=	LGPL21

NO_ARCH=	yes
USE_PYTHON=	autoplist distutils
USES=		python:2 tar:bz2

.include <bsd.port.mk>
