# Created by: Phil Phillips <pphillips@experts-exchange.com>
# $FreeBSD: head/graphics/rubygem-chunky_png/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	chunky_png
PORTVERSION=	1.2.9
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	pphillips@experts-exchange.com
COMMENT=	Ruby library to read and write PNG images

LICENSE=	MIT

USE_RAKE=	yes
NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
