# Created by: chinsan
# $FreeBSD: head/devel/p5-Perl6-Export-Attrs/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	Perl6-Export-Attrs
PORTVERSION=	0.0.3
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	The Perl 6 'is export(...)' trait as a Perl 5 attribute

BUILD_DEPENDS=	p5-Attribute-Handlers>=0:${PORTSDIR}/devel/p5-Attribute-Handlers
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
