# Created by: Gerrit Beine (<tux@pinguru.net>)
# $FreeBSD: head/net/pear-Net_LDAP/Makefile 369094 2014-09-23 16:57:57Z bapt $

PORTNAME=	Net_LDAP
DISTVERSION=	1.1.5
PORTREVISION=	1
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	OO interface for searching and manipulating LDAP-entries

USES=	pear

.include <bsd.port.mk>
