# Created by: alepulver@FreeBSD.org
# $FreeBSD: head/deskutils/menumaker/Makefile 392988 2015-07-27 15:35:05Z jgh $

PORTNAME=	menumaker
PORTVERSION=	0.99.8
CATEGORIES=	deskutils
MASTER_SITES=	SF/${PORTNAME}

MAINTAINER=	jgh@FreeBSD.org
COMMENT=	Menu generator for X Window Managers and desktop environments

USES=		gmake python:2.7+
GNU_CONFIGURE=	yes

INFO=		mmaker

.include <bsd.port.mk>
