# Created by: Bill Fumerola <billf@mu.org>
# $FreeBSD: head/net/tshark/Makefile 378526 2015-02-06 10:52:50Z antoine $

PORTNAME=	tshark
PORTREVISION=	1
CATEGORIES=	net ipv6

MASTERDIR=	${.CURDIR}/../wireshark

OPTIONS_EXCLUDE=	X11 GTK3 QT5

.include "${MASTERDIR}/Makefile"
