# $FreeBSD: head/devel/rubygem-highline/Makefile 394143 2015-08-13 17:36:50Z sunpoet $

PORTNAME=	highline
PORTVERSION=	1.7.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	High-level IO library for command-line interfaces

LICENSE=	GPLv2

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
