# $FreeBSD: head/www/py-plone.intelligenttext/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	plone.intelligenttext
PORTVERSION=	2.0.2
PORTREVISION=	1
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Transforms from text/x-web-intelligent to text/html

LICENSE=	GPLv2

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
