# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: head/www/rubygem-wasabi/Makefile 354970 2014-05-24 01:59:10Z swills $

PORTNAME=	wasabi
PORTVERSION=	1.0.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	Library for simple WSDL parsing

LICENSE=	MIT

RUN_DEPENDS=	rubygem-nokogiri>=1.6.1:${PORTSDIR}/textproc/rubygem-nokogiri

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
