# $FreeBSD: head/www/elixir-joken/Makefile 392562 2015-07-20 11:34:15Z vanilla $

PORTNAME=	joken
PORTVERSION=	0.15.0
DISTVERSIONPREFIX=	v
CATEGORIES=	www
PKGNAMEPREFIX=	elixir-

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	JSON Web Token implementation in Elixir

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	bryanjos

.include <bsd.port.mk>
