# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-EnthoughtBase/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	EnthoughtBase
PORTVERSION=	3.1.0
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	http://enthought.com/repo/ets/ \
		CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Core Packages for the Enthought Tool Suite

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
