# $FreeBSD: head/devel/py-astroid/Makefile 383100 2015-04-03 08:21:38Z mva $

PORTNAME=	astroid
PORTVERSION=	1.3.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	mva@FreeBSD.org
COMMENT=	Extension for Python compiler.ast module

LICENSE=	LGPL21

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}logilab-common>0:${PORTSDIR}/devel/py-logilab-common

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
