# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/www/pear-Services_OpenSearch/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_OpenSearch
PORTVERSION=	0.2.0
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Search A9 OpenSearch compatible engines

BUILD_DEPENDS=	${PEARDIR}/XML/Serializer.php:${PORTSDIR}/devel/pear-XML_Serializer \
		${PEARDIR}/XML/RSS.php:${PORTSDIR}/devel/pear-XML_RSS

USES=	pear

.include <bsd.port.mk>
