# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/textproc/pear-XML_HTMLSax/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	XML_HTMLSax
PORTVERSION=	2.1.2
CATEGORIES=	textproc devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR SAX parser for HTML and other badly formed XML documents

USES=	pear

.include <bsd.port.mk>
