# Created by: Tom Judge <tom@tomjudge.com>
# $FreeBSD: head/databases/py-MySQLdb51/Makefile 343503 2014-02-09 14:15:28Z rm $

PKGNAMESUFFIX=	51

COMMENT=	Access a MySQL database through Python (Using MySQL 5.1 Client)

WANT_MYSQL_VER=	51
MASTERDIR=	${.CURDIR}/../py-MySQLdb

.include "${MASTERDIR}/Makefile"
