# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/sysutils/rubygem-sys-uname/Makefile 394841 2015-08-20 08:43:43Z sunpoet $

PORTNAME=	sys-uname
PORTVERSION=	1.0.1
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby interface for getting system information

LICENSE=	ART20

RUN_DEPENDS=	rubygem-ffi>=1.0.0:${PORTSDIR}/devel/rubygem-ffi

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
