# $FreeBSD: head/devel/pear-Horde_Queue/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Queue
PORTVERSION=	1.1.2
CATEGORIES=	devel www pear
PKGNAMEPREFIX=	pear-

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Queue

USES=	horde

.include <bsd.port.mk>
