# Created by: joerg
# $FreeBSD: head/games/xonix/Makefile 344605 2014-02-16 16:17:51Z miwi $

PORTNAME=	xonix
PORTVERSION=	1.4
PORTREVISION=	3
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	Try to win land without colliding with `flyers' and `eaters'

USES=		imake
USE_XORG=	xaw

.include <bsd.port.mk>
