# Created by: Douglas K. Rand <rand@meridian-enviro.com>
# $FreeBSD: head/comms/libirman/Makefile 365449 2014-08-20 12:28:10Z amdmi3 $

PORTNAME=	libirman
PORTVERSION=	0.4.5
PORTREVISION=	2
CATEGORIES=	comms
MASTER_SITES=	SF/lirc/${PORTNAME}/${PORTVERSION}

MAINTAINER=	rand@meridian-enviro.com
COMMENT=	Library for Evation's Irman infrared receiver

LICENSE=	LGPL20

USES=		gmake libtool tar:bzip2
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
