# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: head/devel/py-phonenumbers/Makefile 393519 2015-08-04 13:27:00Z demon $

PORTNAME=	phonenumbers
PORTVERSION=	7.0.8
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Library for parsing, formatting, and validating intl phone numbers

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
