# $FreeBSD: head/www/erlang-cowlib/Makefile 391484 2015-07-06 22:34:11Z olgeni $

PORTNAME=	cowlib
PORTVERSION=	1.0.0
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	www
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang support library for manipulating Web protocols

LICENSE=	ISCL

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	ninenines

.include <bsd.port.mk>
