# $FreeBSD: head/x11-drivers/xf86-input-mutouch/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-input-mutouch
PORTVERSION=	1.3.0
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org mutouch input driver

XORG_CAT=	driver

.include <bsd.port.mk>
