# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/pear-Console_Color/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Console_Color
PORTVERSION=	1.0.3
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR use ANSI console colors

USES=	pear

.include <bsd.port.mk>
