#!/bin/sh
#
# $FreeBSD: head/editors/openoffice-devel/files/openoffice-wrapper 340872 2014-01-24 00:14:07Z mat $

oopath=%%PREFIX%%/%%INSTALLATION_BASEDIR%%/%%OOODIR%%
program=`echo $0 | sed -e 's|.*-%%SVNREVISION%%-||'`

case $program in
$0)
	$oopath/program/soffice "$@"
	;;
setofficelang)
	$oopath/basis-link/program/$program "$@"
	;;
*)
	$oopath/program/$program "$@"
	;;
esac
