# Created by: Bill Brinzer <bill.brinzer@gmail.com>
# $FreeBSD: head/devel/p5-Capture-Tiny/Makefile 379528 2015-02-21 15:58:21Z adamw $

PORTNAME=	Capture-Tiny
PORTVERSION=	0.28
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAGOLDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bill.brinzer@gmail.com
COMMENT=	Capture STDOUT and STDERR from Perl, XS, or external programs

LICENSE=	APACHE20

TEST_DEPENDS=	p5-Inline>=0.50:${PORTSDIR}/devel/p5-Inline

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
