# Created by: Antonio Carlos Venancio Junior (<antonio@php.net>)
# $FreeBSD: head/devel/pear-Validate/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Validate
PORTVERSION=	0.8.5
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR Validation class

USES=	pear

.include <bsd.port.mk>
