# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-annoy/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	annoy
PORTVERSION=	0.5.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Present the user with a simple question before a destructive action

LICENSE=	MIT

RUN_DEPENDS=	rubygem-highline>=1.5.0:${PORTSDIR}/devel/rubygem-highline

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
