# $FreeBSD: head/www/rubygem-d3_rails/Makefile 392416 2015-07-18 11:13:52Z sunpoet $

PORTNAME=	d3_rails
PORTVERSION=	3.5.6
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	JavaScript framework for data visualization

LICENSE=	MIT

RUN_DEPENDS=	rubygem-railties>=3.1.0:${PORTSDIR}/www/rubygem-railties

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
