# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/net/p5-RPC-Simple/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	RPC-Simple
PORTVERSION=	1.002
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Perl classes to handle simple asynchronous RPC calls with call-back

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
