# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11/nvidia-driver-340/Makefile 378360 2015-02-03 16:18:34Z danfe $

DISTVERSION=	340.76
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-340

.include "${MASTERDIR}/Makefile"
