# $FreeBSD: head/x11-drivers/xf86-input-synaptics/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	xf86-input-synaptics
PORTVERSION=	1.8.2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org synaptics input driver

CONFLICTS=	synaptics-[0-9]*

USES=		pathfix
USE_XORG=	x11 xtst
XORG_CAT=	driver

.include <bsd.port.mk>
