# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/xproto/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	xproto
PORTVERSION=	7.0.27
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 protocol headers

XORG_CAT=	proto

CONFIGURE_ARGS+=--disable-specs --without-fop --without-xmlto --without-xsltproc

.include <bsd.port.mk>
