# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/converters/p5-Encoding-FixLatin/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Encoding-FixLatin
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:GRANTM
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Takes mixed encoding input and produces UTF-8 output

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
