# Created by: Greg Larkin <glarkin@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-childprocess/Makefile 390811 2015-06-28 17:54:19Z sunpoet $

PORTNAME=	childprocess
PORTVERSION=	0.5.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	External background process controller

LICENSE=	MIT

RUN_DEPENDS=	rubygem-ffi>=1.0.11:${PORTSDIR}/devel/rubygem-ffi

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
