# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: head/math/p5-Math-Random-MT/Makefile 374217 2014-12-07 16:31:50Z feld $

PORTNAME=	Math-Random-MT
PORTVERSION=	1.16
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	The Mersenne Twister PRNG

LICENSE=	BSD3CLAUSE

TEST_DEPENDS=	p5-Test-Number-Delta>=0:${PORTSDIR}/devel/p5-Test-Number-Delta

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
