# $FreeBSD: head/www/erlang-ibrowse/Makefile 394599 2015-08-18 15:11:03Z olgeni $

PORTNAME=	ibrowse
PORTVERSION=	4.1.2
DISTVERSIONPREFIX=	v
CATEGORIES=	www
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	HTTP client library for Erlang

LICENSE=	BSD3CLAUSE LGPL21
LICENSE_COMB=	dual

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	cmullaparthi

.include <bsd.port.mk>
