# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/security/pear-Crypt_XXTEA/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Crypt_XXTEA
PORTVERSION=	0.9.0
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR XXTEA encryption algorithm

USES=	pear

.include <bsd.port.mk>
