# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD: head/devel/libserver/Makefile 388916 2015-06-09 12:50:08Z amdmi3 $

PORTNAME=	libserver
PORTVERSION=	2.1.5
CATEGORIES=	devel
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	Generic TCP server in a library

LICENSE=	BSD3CLAUSE

USE_LDCONFIG=	yes

MAKE_ENV+=	STAGEDIR=${STAGEDIR}
PLIST_SUB+=	PORTVERSION=${PORTVERSION}

.include <bsd.port.mk>
