# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/p5-Math-Random-ISAAC-XS/Makefile 381259 2015-03-14 10:55:45Z wen $

PORTNAME=	Math-Random-ISAAC-XS
PORTVERSION=	1.004
PORTREVISION=	2
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JAWNSY
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	C implementation of the ISAAC PRNG Algorithm

TEST_DEPENDS=	p5-Test-NoWarnings>0:${PORTSDIR}/devel/p5-Test-NoWarnings

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
