# $FreeBSD: head/x11-drivers/xf86-input-mouse/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	xf86-input-mouse
PORTVERSION=	1.9.1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org mouse input driver

XORG_CAT=	driver
USES=		pathfix

.include <bsd.port.mk>
