# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-HTML_Page2/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_Page2
PORTVERSION=	0.6.1
CATEGORIES=	devel www pear
DISTNAME=	${PORTNAME}-${PORTVERSION}beta

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR base class for XHTML page generation

BUILD_DEPENDS=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common
RUN_DEPENDS=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common

USES=	pear

.include <bsd.port.mk>
