# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: head/audio/gstreamer-plugins-soundtouch/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/audio/gstreamer-plugins-soundtouch/Makefile,v 1.3 2008/03/19 14:05:32 ahze Exp $

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	GStreamer soundtouch plugin

GST_PLUGIN=	soundtouch

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
