# Created by: Jason W. Bacon <jwbacon@tds.net>
# $FreeBSD: head/sysutils/endian/Makefile 359646 2014-06-28 04:15:57Z danilo $

PORTNAME=	endian
PORTVERSION=	1.1
CATEGORIES=	sysutils
MASTER_SITES=	http://acadix.biz/Ports/distfiles/ \
		http://personalpages.tds.net/~jwbacon/Ports/distfiles/ 

MAINTAINER=	jwbacon@tds.net
COMMENT=	Report endianness of a system

LICENSE=	BSD2CLAUSE

USES=		tar:xz

PLIST_FILES=	bin/endian man/man1/endian.1.gz

MAKE_ARGS=	STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
