# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/math/R-cran-Zelig/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	Zelig
DISTVERSION=	4.2-1
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Everyone's Statistical Software

BUILD_DEPENDS=	R-cran-sandwich>=0:${PORTSDIR}/math/R-cran-sandwich
RUN_DEPENDS=	R-cran-sandwich>=0:${PORTSDIR}/math/R-cran-sandwich

USES=	cran:auto-plist

.include <bsd.port.mk>
