# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-iterators/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	iterators
PORTVERSION=	1.0.7
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Iterator construct for R

LICENSE=	APACHE20

USES=	cran:auto-plist

.include <bsd.port.mk>
