# Created by: Nick Hilliard <nick@foobar.org>
# $FreeBSD: head/www/pear-Structures_DataGrid_Renderer_Pager/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Structures_DataGrid_Renderer_Pager
PORTVERSION=	0.1.3
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Pager Renderer for pear-Structures_DataGrid

RUN_DEPENDS=	${PEARDIR}/Structures/DataGrid.php:${PORTSDIR}/devel/pear-Structures_DataGrid \
		${PEARDIR}/Pager/Pager.php:${PORTSDIR}/devel/pear-Pager

USES=	pear

.include <bsd.port.mk>
