# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/astro/R-cran-maptools/Makefile 385444 2015-05-05 04:44:17Z tota $

PORTNAME=	maptools
DISTVERSION=	0.8-36
CATEGORIES=	astro
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for reading and handling spatial objects

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-sp>=1.0.11:${PORTSDIR}/math/R-cran-sp

USES=	cran:auto-plist

.include <bsd.port.mk>
