# Created by: Jason Burgess <dev@fenux.net>
# $FreeBSD: head/converters/p5-Convert-IBM390/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Convert-IBM390
PORTVERSION=	0.27
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Functions for manipulating mainframe data

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
