# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/archivers/pear-PHP_Archive/Makefile 391809 2015-07-12 16:08:56Z sunpoet $

PORTNAME=	PHP_Archive
PORTVERSION=	0.12.0
CATEGORIES=	archivers pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Create and Use PHP Archive files

LICENSE=	PHP301

NO_ARCH=	yes
USES=		pear

.include <bsd.port.mk>
