# Created by: Dmitry Pryadko <d.pryadko@rambler-co.ru>
# $FreeBSD: head/dns/py-publicsuffix/Makefile 371188 2014-10-19 15:43:33Z mva $

PORTNAME=	publicsuffix
PORTVERSION=	1.0.4
CATEGORIES=	dns python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	d.pryadko@rambler-co.ru
COMMENT=	Get public suffix of domain name from Public Suffix List

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
