# $FreeBSD: head/emulators/mess/Makefile 387368 2015-05-25 07:29:14Z marino $

PORTNAME=	mess
MTARGET=	mess
COMMENT=	Multiple Emulator Super System

MASTERDIR=	${.CURDIR}/../mame
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
