# $FreeBSD: head/sysutils/py-queuelib/Makefile 367998 2014-09-12 01:33:18Z jhale $

PORTNAME=	queuelib
PORTVERSION=	1.2.2
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jhale@FreeBSD.org
COMMENT=	Collection of persistent (disk-based) queues

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
