# Created by: Joe Horn <joehorn@gmail.com>
# $FreeBSD: head/www/pecl-twig/Makefile 355036 2014-05-24 14:12:43Z sunpoet $

PORTNAME=	twig
PORTVERSION=	1.15.1
CATEGORIES=	www
MASTER_SITES=	http://pear.twig-project.org/get/
PKGNAMEPREFIX=	pecl-
DISTNAME=	CTwig-${PORTVERSION}

MAINTAINER=	joehorn@gmail.com
COMMENT=	Twig C extension to improve performance of the Twig template language

LICENSE=	BSD3CLAUSE

USE_PHP=	yes
USE_PHPIZE=	yes
USE_PHPEXT=	yes
USES=		tar:tgz

.include <bsd.port.mk>
