# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-irlba/Makefile 393972 2015-08-11 20:41:29Z tota $

PORTNAME=	irlba
PORTVERSION=	1.0.3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Fast partial SVD by implicitly-restarted Lanczos bidiagonalization

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	cran:auto-plist

.include <bsd.port.mk>
