# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/devel/pear-Validate_US/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Validate_US
PORTVERSION=	0.5.5
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR data validation class for US

BUILD_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate
RUN_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate

USES=	pear

.include <bsd.port.mk>
