# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/security/pear-Crypt_CHAP/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Crypt_CHAP
PORTVERSION=	1.5.0
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class for generating CHAP packets

USES=	pear
USE_PHP=	mcrypt mhash

.include <bsd.port.mk>
