# $FreeBSD: head/x11-fonts/libFS/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libFS
PORTVERSION=	1.0.6
PORTREVISION=	2
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The FS library

XORG_CAT=	lib
USE_XORG=	fontsproto:both xproto:both xtrans
USES+=	cpe
CPE_PRODUCT=	libfs
CPE_VENDOR=	x

.include <bsd.port.mk>
