# Created by: petef@databits.net
# $FreeBSD: head/textproc/p5-PDF-Create/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	PDF-Create
PORTVERSION=	1.10
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Perl script to convert text files to PDF files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
