# Created by: Felippe de Meirelles Motta <lippemail@gmail.com>
# $FreeBSD: head/net/p5-Net-Google-AuthSub/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-Google-AuthSub
PORTVERSION=	0.5
PORTREVISION=	2
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lippe@FreeBSD.org
COMMENT=	Interact with sites that implement Google style AuthSub

RUN_DEPENDS=	p5-URI>=0:${PORTSDIR}/net/p5-URI \
		p5-libwww>=0:${PORTSDIR}/www/p5-libwww

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
