# Created by: Pav Lucistnik <pav@FreeBSD.org>
# $FreeBSD: head/archivers/rzip/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	rzip
PORTVERSION=	2.1
CATEGORIES=	archivers
MASTER_SITES=	SAMBA/rzip

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Compression program similar to gzip or bzip2

LICENSE=	GPLv2

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/rzip man/man1/rzip.1.gz

.include <bsd.port.mk>
