# $FreeBSD: head/chinese/libreoffice-zh_CN/Makefile 371023 2014-10-16 21:14:18Z jkim $

LO_I18N=	zh_CN
LO_HAS_HELPPACK=	yes
CATEGORIES=	chinese editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
