# $FreeBSD: head/x11-drivers/xf86-video-sis/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-video-sis
PORTVERSION=	0.10.7
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org sis display driver

CONFLICTS=	xf86-video-sis-intel-[0-9]*

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86dgaproto xf86driproto xineramaproto xf86miscproto glproto

.include <bsd.port.mk>
