# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/security/pear-Auth_PrefManager/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Auth_PrefManager
PORTVERSION=	1.2.2
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR preferences management class

USES=	pear

.include <bsd.port.mk>
