# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD: head/x11-wm/nickleby/Makefile 382675 2015-03-30 15:20:52Z pawel $

PORTNAME=	nickleby
PORTVERSION=	2.2.1
CATEGORIES=	x11-wm
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	Simple window manager

USE_XORG=	x11
DESTDIRNAME=	STAGEDIR

PLIST_FILES=	bin/nickleby \
		man/man1/nickleby.1.gz

.include <bsd.port.mk>
