# $FreeBSD: head/devel/erlang-meck/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	meck
PORTVERSION=	0.8.3
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang library for building mock modules

LICENSE=	APACHE20

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	eproxus

.include <bsd.port.mk>
