# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/archivers/php56-zip/Makefile 395464 2015-08-28 10:48:41Z makc $

PORTREVISION=	1
CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-zip

.include "${MASTERDIR}/Makefile"
