# $FreeBSD: head/devel/p5-Module-CPANfile/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Module-CPANfile
PORTVERSION=	1.1000
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Parse cpanfile

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
