# Created by: Espen Volden aka voldern <voldern@hoeggen.net>
# $FreeBSD: head/databases/rubygem-data_objects/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	data_objects
PORTVERSION=	0.10.13
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	voldern@hoeggen.net
COMMENT=	Unified Ruby API for popular databases

RUN_DEPENDS=	rubygem-addressable>=2.1:${PORTSDIR}/www/rubygem-addressable

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
