# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/devel/py-flexmock/Makefile 373790 2014-12-02 22:40:56Z bapt $

PORTNAME=	flexmock
PORTVERSION=	0.9.7
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Flexmock is a mock/stub/spy library for Python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
