# Created by: Christer Edwards <christer.edwards@gmail.com>
# $FreeBSD: head/net/py-raet/Makefile 386105 2015-05-11 21:38:18Z robak $

PORTNAME=	raet
PORTVERSION=	0.6.3
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	christer.edwards@gmail.com
COMMENT=	Reliable Asynchronous Event Transport protocol library

LICENSE=	APACHE20

USES=		python:2
USE_PYTHON=	distutils

.include <bsd.port.mk>
