# $FreeBSD: head/textproc/py-junit-xml/Makefile 374183 2014-12-07 10:01:36Z mva $

PORTNAME=	junit-xml
PORTVERSION=	1.3
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Creates JUnit XML documents used by tools such as Jenkins

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
