# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/net/pear-Net_CheckIP/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_CheckIP
PORTVERSION=	1.2.2
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Check the syntax of IPv4 addresses

USES=	pear

.include <bsd.port.mk>
