# Created by: Antonio Carlos Venancio Junior (<antonio@php.net>)
# $FreeBSD: head/devel/pear-HTML_Form/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_Form
PORTVERSION=	1.3.0
PORTREVSION=	1
CATEGORIES=	devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR simple HTML form package

USES=	pear

.include <bsd.port.mk>
