# $FreeBSD: head/textproc/rubygem-twitter-text/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	twitter-text
PORTVERSION=	1.12.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby gem for handling of Twitter texts

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-unf>=0.1.0:${PORTSDIR}/textproc/rubygem-unf

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
