# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/net/rubygem-fog-softlayer/Makefile 390455 2015-06-23 20:26:56Z sunpoet $

PORTNAME=	fog-softlayer
PORTVERSION=	0.4.7
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provider to use the SoftLayer Cloud in applications

LICENSE=	MIT

RUN_DEPENDS=	rubygem-fog-core>=0:${PORTSDIR}/devel/rubygem-fog-core \
		rubygem-fog-json>=0:${PORTSDIR}/devel/rubygem-fog-json

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
