# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/www/py-WebFlash/Makefile 371124 2014-10-18 13:18:19Z rm $

PORTNAME=	WebFlash
PORTVERSION=	0.1a9
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wenheping@gmail.com
COMMENT=	Library to display flash messages in python web applications

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
