# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: head/www/py-tvdb_api/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	tvdb_api
PORTVERSION=	1.9
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	API interface to TheTVDB.com

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
