# $FreeBSD: head/devel/py-zc.buildout/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	zc.buildout
PORTVERSION=	2.2.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	rm@FreeBSD.org
COMMENT=	System for managing development buildouts

LICENSE=	ZPL21

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
