# Created by: Roman Bogorodskiy <novel@FreeBSD.org>
# $FreeBSD: head/devel/py-prettytable/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	prettytable
PORTVERSION=	0.7.2
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP/source/P/PrettyTable
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	novel@FreeBSD.org
COMMENT=	Library for displaying tabular data in an ASCII table format

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
