# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/www/pear-Services_TwitPic/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_TwitPic
PORTVERSION=	0.1.0
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP Interface to TwitPic's API

USES=	pear

.include <bsd.port.mk>
