# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/databases/pear-DB_ldap/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	DB_ldap
PORTVERSION=	1.2.1
CATEGORIES=	databases net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR DB compliant interface to LDAP servers

BUILD_DEPENDS=	${PEARDIR}/DB.php:${PORTSDIR}/databases/pear-DB
RUN_DEPENDS=	${PEARDIR}/DB.php:${PORTSDIR}/databases/pear-DB

USES=		pear

.include <bsd.port.mk>
