# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-mspec/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	mspec
PORTVERSION=	1.5.21
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Specialized Ruby testing framework

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/mkspec bin/mspec bin/mspec-ci bin/mspec-run bin/mspec-tag

.include <bsd.port.mk>
