# Created by: loader <loader@freebsdmall.com>
# $FreeBSD: head/devel/p5-File-Tempdir/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Tempdir
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	loader@freebsdmall.com
COMMENT=	Perl5 module to provide an object interface for File::Temp

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
