# Created by: Byung-Hee HWANG <bh@izb.knu.ac.kr>
# $FreeBSD: head/audio/py-mutagen/Makefile 387970 2015-05-30 14:42:15Z olivierd $

PORTNAME=	mutagen
PORTVERSION=	1.29
CATEGORIES=	audio python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	johnson.peter@gmail.com
COMMENT=	Python-based audio metadata tag reader and writer

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
