# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/net/pear-Net_Socket/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_Socket
PORTVERSION=	1.0.14
CATEGORIES=	net www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR Network Socket Interface

USES=	pear

.include <bsd.port.mk>
