# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/science/py-DendroPy/Makefile 387529 2015-05-27 00:15:04Z amdmi3 $

PORTNAME=	DendroPy
PORTVERSION=	3.12.0
PORTREVISION=	1
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Phylogenetic computing library

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
