# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/graphics/p5-Image-Base/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Image-Base
PORTVERSION=	1.17
PORTREVISION=	1
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Base class for loading, manipulating, and saving images

LICENSE=	LGPL3

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
