# Created by: Sofian Brabez <sbz@FreeBSD.org>
# $FreeBSD: head/x11-toolkits/py-SquareMap/Makefile 371203 2014-10-19 18:16:15Z mva $

PORTNAME=	SquareMap
PORTVERSION=	1.0.4
PORTREVISION=	1
CATEGORIES=	x11-toolkits python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sbz@FreeBSD.org
COMMENT=	Hierarchic visualization control for wxPython

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist
USE_WX=		2.8
WX_COMPS=	python

.include <bsd.port.mk>
