# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/www/pear-HTTP_Upload/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTTP_Upload
PORTVERSION=	0.9.1
CATEGORIES=	www devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Easy and secure management of files submitted via HTML Forms

USES=	pear

.include <bsd.port.mk>
