# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/net/pear-Services_Pingback/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_Pingback
PORTVERSION=	0.2.2
CATEGORIES=	net www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Pingback user-agent class

USES=	pear

.include <bsd.port.mk>
