# Created by: Yoshihiko Sarumaru <mistral@imasy.or.jp>
# $FreeBSD: head/x11-fonts/bdfresize/Makefile 364347 2014-08-08 08:42:44Z olgeni $

PORTNAME=	bdfresize
PORTVERSION=	1.5
PORTREVISION=	2
CATEGORIES=	x11-fonts
MASTER_SITES=	http://openlab.ring.gr.jp/efont/dist/tools/bdfresize/

MAINTAINER=	sarumaru@jp.FreeBSD.org
COMMENT=	Tool for resizing BDF format font

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/bdfresize \
		man/man1/bdfresize.1.gz

.include <bsd.port.mk>
