# $FreeBSD: head/devel/elixir-decimal/Makefile 391241 2015-07-03 13:59:45Z olgeni $

PORTNAME=	decimal
PORTVERSION=	1.1.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Arbitrary precision decimal arithmetic for Elixir

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	ericmj

.include <bsd.port.mk>
