# Created by: Mario S F Ferreira <lioux@FreeBSD.org>
# $FreeBSD: head/math/p5-Math-Interpolate/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Math-Interpolate
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Perl routines for data sets interpolation and interval search

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
