# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/converters/pear-Services_JSON/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_JSON
PORTVERSION=	1.0.3
CATEGORIES=	converters www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP implementation of json_encode/decode

USES=		pear

.include <bsd.port.mk>
