# Created by: tobias.rehbein@web.de
# $FreeBSD: head/games/stonesoup-sdl/Makefile 387490 2015-05-26 16:35:41Z amdmi3 $

PORT_OPTIONS+=	SDL

MASTERDIR=	${.CURDIR}/../stonesoup

.include	"${MASTERDIR}/Makefile"
