# Created by: antoine@FreeBSD.org
# $FreeBSD: head/textproc/py-acora/Makefile 365714 2014-08-23 08:16:57Z antoine $

PORTNAME=	acora
PORTVERSION=	1.8
CATEGORIES=	textproc devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Fast multi-keyword search engine for text strings

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
