# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: head/archivers/p5-Compress-Bzip2/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Compress-Bzip2
PORTVERSION=	2.17
PORTREVISION=	1
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Perl5 interface to bzip2 compression library

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
