# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/textproc/py-Chameleon/Makefile 388245 2015-06-01 18:30:30Z rm $

PORTNAME=	Chameleon
DISTVERSION=	2.22
CATEGORIES=	textproc www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Fast HTML/XML Template Compiler

LICENSE=	BSD4CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
