# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/sysutils/pear-File_Find/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	File_Find
PORTVERSION=	1.3.3
CATEGORIES=	sysutils www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class that facilitates the search of filesystems

LICENSE=	PHP301

USES=	pear

.include <bsd.port.mk>
