# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/astro/p5-Misc-Quality/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Misc-Quality
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	astro perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:AALLAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Class for handling quality flags for astronomical objects

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
