# Created by: Oleg Ukraincev <oleg@ht-systems.ru>
# $FreeBSD: head/devel/py-polib/Makefile 381548 2015-03-18 13:07:40Z wg $

PORTNAME=	polib
PORTVERSION=	1.0.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Python library to parse and manage gettext catalogs

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
