# Created by: Michael Moll <kvedulv@kvedulv.de>
# $FreeBSD: head/textproc/rubygem-jekyll-paginate/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	jekyll-paginate
PORTVERSION=	1.1.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Built-in Pagination Generator for Jekyll

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
