# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: head/databases/courier-authlib-usergdbm/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTREVISION=	1
PKGNAMESUFFIX=	-usergdbm

COMMENT=	Userdb support for the Courier authentication library
CATEGORIES=	databases mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

.include "${MASTERDIR}/Makefile"
