# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/devel/pear-codegen/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	codegen
PORTVERSION=	1.0.7
CATEGORIES=	devel pear
DISTNAME=	CodeGen-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tool to create code generators that operate on XML descriptions

USES=	pear

.include <bsd.port.mk>
