# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: head/devel/rubygem-sequel3/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

# legacy for rubygem-larch

PORTNAME=	sequel
PORTVERSION=	3.48.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	3

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	The Database Toolkit for Ruby

LICENSE=	MIT

PORTSCOUT=	limit:^3

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes

PLIST_FILES=	bin/sequel

.include <bsd.port.mk>
