# $FreeBSD: head/textproc/py-trans/Makefile 374183 2014-12-07 10:01:36Z mva $

PORTNAME=	trans
PORTVERSION=	2.0
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	d.pryadko@rambler-co.ru
COMMENT=	Module for performing transliteration

LICENSE=	BSD

USES=		python tar:bzip2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
