# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: head/www/rubygem-semantic-ui-sass/Makefile 390398 2015-06-23 12:23:11Z sunpoet $

PORTNAME=	semantic-ui-sass
PORTVERSION=	1.11.5.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Semantic UI, converted to Sass and ready to drop into Rails & Compass

LICENSE=	MIT

RUN_DEPENDS=	rubygem-sass>=3.2:${PORTSDIR}/textproc/rubygem-sass

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
