# $FreeBSD: head/x11-drivers/xf86-video-dummy/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-video-dummy
PORTVERSION=	0.3.7
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org dummy display driver

XORG_CAT=	driver
USE_XORG=	xf86dgaproto

.include <bsd.port.mk>
