# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/devel/pear-Date/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Date
PORTVERSION=	1.4.7
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR Date and Time Zone Classes

USES=		pear

.include <bsd.port.mk>
