# $FreeBSD: head/devel/py-path.py/Makefile 369278 2014-09-25 17:15:51Z wg $

PORTNAME=	path.py
PORTVERSION=	6.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Module wrapper for os.path

LICENSE=	MIT

USES=		python zip
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
