# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD: head/devel/rubygem-ice_cube/Makefile 393819 2015-08-09 19:34:06Z swills $

PORTNAME=	ice_cube
PORTVERSION=	0.13.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@freebsd.org
COMMENT=	Recurring date library for Ruby

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
