# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/net/pear-Net_URL2/Makefile 370667 2014-10-11 20:06:14Z gerald $

PORTNAME=	Net_URL2
PORTVERSION=	2.0.10
CATEGORIES=	net www pear

MAINTAINER=	joehorn@gmail.com
COMMENT=	PEAR Class for parsing and handling URL

LICENSE=	BSD3CLAUSE

USES=	pear

.include <bsd.port.mk>
