# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: head/textproc/rubygem-version_sorter/Makefile 379500 2015-02-21 11:31:53Z sunpoet $

PORTNAME=	version_sorter
PORTVERSION=	2.0.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast sorting of version strings

LICENSE=	MIT

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
