# $FreeBSD: head/devel/elixir-plug/Makefile 394615 2015-08-18 16:09:28Z olgeni $

PORTNAME=	plug
PORTVERSION=	1.0.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Composable modules for Elixir web applications

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	elixir-lang

.include <bsd.port.mk>
