# Created by: Ulrich Spoerlein <uspoerlein@gmail.com>
# $FreeBSD: head/devel/librcd/Makefile 364733 2014-08-12 18:43:26Z amdmi3 $

PORTNAME=	librcd
PORTVERSION=	0.1.14
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	http://dside.dyndns.org/files/rusxmms/ \
		LOCAL/fluffy

MAINTAINER=	fluffy@FreeBSD.org
COMMENT=	Library used by rusxmms for autodetection of Russian charset

GNU_CONFIGURE=	yes
USES=		gmake libtool pathfix tar:bzip2
USE_LDCONFIG=	yes

.include <bsd.port.mk>
