# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/www/pear-Services_Compete/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_Compete
PORTVERSION=	0.1.0
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP interface to Compete SnapShop API

BUILD_DEPENDS=	${PEARDIR}/HTTP/Request.php:${PORTSDIR}/www/pear-HTTP_Request
RUN_DEPENDS=	${PEARDIR}/HTTP/Request.php:${PORTSDIR}/www/pear-HTTP_Request

USES=	pear

.include <bsd.port.mk>
