# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: head/games/p5-Games-Tournament-RoundRobin/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Games-Tournament-RoundRobin
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	games perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Round-Robin Tournament Schedule Pairings

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
