# $FreeBSD: head/textproc/rubygem-rouge/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	rouge
PORTVERSION=	1.9.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Simple, easy-to-extend drop-in replacement for pygments

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/rougify

.include <bsd.port.mk>
