# $FreeBSD: head/french/libreoffice/Makefile 371023 2014-10-16 21:14:18Z jkim $

LO_I18N=	fr
LO_HAS_HELPPACK=	yes
CATEGORIES=	french editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
