# Created by: Alex Kapranoff <alex@kapranoff.ru>
# $FreeBSD: head/devel/p5-Test-LectroTest/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Test-LectroTest
PORTVERSION=	0.5001
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lippe@FreeBSD.org
COMMENT=	Easy, automatic, specification-based tests

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
