# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/audio/pear-Text_Spell_Audio/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Text_Spell_Audio
PORTVERSION=	0.1.0
CATEGORIES=	audio pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Generates a sound clip saying the contents of a string of characters

USES=	pear

.include <bsd.port.mk>
