# Created by: William Grzybowski <william88@gmail.com>
# $FreeBSD: head/devel/py-billiard/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	billiard
PORTVERSION=	3.3.0.18
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Python multiprocessing fork with improvements and bugfixes

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
