# Created by: J.R. Oldroyd <fbsd@opal.com>
# $FreeBSD: head/devel/libburn/Makefile 386875 2015-05-20 18:30:06Z olivierd $

PORTNAME=	libburn
PORTVERSION=	1.4.0
CATEGORIES=	devel
MASTER_SITES=	http://files.libburnia-project.org/releases/

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	Libburnia library to read/write optical discs

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
