# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-HTML_QuickForm_SelectFilter/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_QuickForm_SelectFilter
PORTVERSION=	1.0.0
CATEGORIES=	devel www pear
DISTNAME=	${PORTNAME}-${PORTVERSION}RC1

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Element for PEAR::HTML_QuickForm that defines dynamic filters

BUILD_DEPENDS=	${PEARDIR}/HTML/QuickForm.php:${PORTSDIR}/devel/pear-HTML_QuickForm
RUN_DEPENDS=	${PEARDIR}/HTML/QuickForm.php:${PORTSDIR}/devel/pear-HTML_QuickForm

USES=	pear

.include <bsd.port.mk>
