# $FreeBSD: head/devel/geany-plugins-l10n/Makefile 369260 2014-09-25 15:18:27Z tijl $

PORTNAME=	geany-plugins-l10n
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Localization messages for Geany plugins

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
