# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-sass/Makefile 395358 2015-08-26 09:31:50Z sunpoet $

PORTNAME=	sass
PORTVERSION=	3.4.18
CATEGORIES=	textproc ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sass is an extension of CSS3

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/sass bin/sass-convert bin/scss

.include <bsd.port.mk>
