# $FreeBSD: head/net/isc-dhcp41-client/Makefile 349269 2014-03-26 17:27:24Z garga $

COMMENT=	The ISC Dynamic Host Configuration Protocol client

SUBSYS=		client
MASTERDIR=	${.CURDIR}/../isc-dhcp41-server

.include "${MASTERDIR}/Makefile"
