# $FreeBSD: head/databases/rubygem-arel/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	arel
PORTVERSION=	5.0.1.20140414130214
PORTEPOCH=	1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Relational Algebra for Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
