# $FreeBSD: head/www/pear-Horde_SessionHandler/Makefile 369674 2014-09-30 22:14:59Z bapt $

PORTNAME=	Horde_SessionHandler
PORTVERSION=	2.2.4
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Session Handler API

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.mk>
