# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libxkbfile/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libxkbfile
PORTVERSION=	1.0.8
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XKB file library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 kbproto:both

.include <bsd.port.mk>
