# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: head/devel/py-pycerberus/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	pycerberus
PORTVERSION=	0.5
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	Highly flexible, no magic input validation library

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
