# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/devel/p5-Test-MockModule/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Test-MockModule
PORTVERSION=	0.05
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Override subroutines in a module for unit testing

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
