# Created by: Hye-Shik Chang
# $FreeBSD: head/devel/py-logilab-common/Makefile 383099 2015-04-03 08:20:06Z mva $

PORTNAME=	logilab-common
PORTVERSION=	0.63.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	mva@FreeBSD.org
COMMENT=	Common low-level libraries shared among logilab projects

LICENSE=	LGPL20

USES=		python
MAKE_ENV=	NO_SETUPTOOLS=1
USE_PYTHON=	distutils concurrent

.include <bsd.port.mk>
