# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/science/py-cdo/Makefile 388611 2015-06-05 18:57:17Z sunpoet $

PORTNAME=	cdo
PORTVERSION=	1.2.6
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Python binding to CDO (Climate Data Operators)

LICENSE=	GPLv2

RUN_DEPENDS=	${LOCALBASE}/bin/cdo:${PORTSDIR}/science/cdo

USE_PYTHON=	autoplist distutils
USES=		python

.include <bsd.port.mk>
