# Created by: Yoshihiko Sarumaru <mistral@imasy.or.jp>
# $FreeBSD: head/net/p5-Net-Wake/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-Wake
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sarumaru@jp.FreeBSD.org
COMMENT=	Send Wake On Lan (WOL) packets to power on computers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
