# Created by: Jin-Sih, Lin <linpct@gmail.com>
# $FreeBSD: head/devel/rubygem-rodzilla/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	rodzilla
PORTVERSION=	0.3.6
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	linpct@gmail.com
COMMENT=	Bugzilla API Client

LICENSE=	MIT

RUN_DEPENDS=	rubygem-httparty>=0.12.0:${PORTSDIR}/www/rubygem-httparty

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
