# Created by: Wen heping <wenheping@gmail.com>
# $FreeBSD: head/www/pear-HTML_TagCloud/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_TagCloud
PORTVERSION=	1.0.0
CATEGORIES=	www devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Generate TagCloud in HTML And Visualize Tags

USES=	pear

.include <bsd.port.mk>
