# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/www/pear-Text_Wiki/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Text_Wiki
PORTVERSION=	1.2.1
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Abstracts parsing and rendering rules for Wiki markup

USES=	pear

.include <bsd.port.mk>
