# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-zoo/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	zoo
DISTVERSION=	1.7-10
PORTREVISION=	4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	S3 Infrastructure for Regular and Irregular Time Series

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
