# $FreeBSD: head/x11-drivers/xf86-video-nv/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-video-nv
PORTVERSION=	2.1.20
PORTREVISION=	6
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org nv display driver

XORG_CAT=	driver

.include <bsd.port.mk>
