# $FreeBSD: head/databases/py-python-sql/Makefile 395167 2015-08-24 12:06:37Z wen $

PORTNAME=	python-sql
PORTVERSION=	0.7
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Library to write SQL queries

#LICENSE=	BSD

USES=		pkgconfig python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
