# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/security/pear-File_HtAccess/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	File_HtAccess
PORTVERSION=	1.2.1
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class to manipulate .htaccess files

USES=	pear

.include <bsd.port.mk>
