# Created by: Thierry Thomas (<thierry@FreeBSD.org>)
# $FreeBSD: head/net/pear-Net_DIME/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_DIME
PORTVERSION=	1.0.2
PORTEPOCH=	1
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	The PEAR::Net_DIME class implements DIME encoding

USES=	pear

.include <bsd.port.mk>
