# $FreeBSD: head/x11/xhost/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	xhost
PORTVERSION=	1.0.6
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Server access control program for X

XORG_CAT=	app
USE_XORG=	x11 xmuu xau

PLIST_FILES=	bin/xhost man/man1/xhost.1.gz

.include <bsd.port.mk>
