# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/www/p5-HTTP-Server-Simple/Makefile 379152 2015-02-17 11:48:28Z lth $

PORTNAME=	HTTP-Server-Simple
PORTVERSION=	0.50
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Simple standalone HTTP daemon

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
