# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-coffee-script-source/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	coffee-script-source
PORTVERSION=	1.9.1.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	CoffeeScript is a little language that compiles into JavaScript

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
