# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/graphics/p5-SVG-DOM2/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	SVG-DOM2
PORTVERSION=	1.00
PORTREVISION=	2
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	SVG extension to the popular XML::DOM2

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
