# $FreeBSD: head/devel/py-blessings/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	blessings
PORTVERSION=	1.5.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Thin wrapper around terminal coloring, styling, and positioning

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
