# $FreeBSD: head/sysutils/pick/Makefile 381992 2015-03-23 13:16:23Z bofh $

PORTNAME=	pick
PORTVERSION=	1.1.1
CATEGORIES=	sysutils
MASTER_SITES=	http://github.com/thoughtbot/pick/releases/download/v${PORTVERSION}/

MAINTAINER=	neel@neelc.org
COMMENT=	Tool for choosing one option from a set of choices with an interface

LICENSE=	MIT

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/pick man/man1/pick.1.gz

.include <bsd.port.mk>
