# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-safe_yaml/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	safe_yaml
PORTVERSION=	1.0.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Parse YAML safely

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/safe_yaml

.include <bsd.port.mk>
