# Created by: Nick Hilliard <nick@foobar.org>
# $FreeBSD: head/devel/pear-Structures_DataGrid/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Structures_DataGrid
PORTVERSION=	0.9.3
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Full-featured tabular structured data management package

RUN_DEPENDS=	${PEARDIR}/Console/Table.php:${PORTSDIR}/devel/pear-Console_Table

USES=	pear

.include <bsd.port.mk>
