# Created by: Sergey A. Osokin <osa@FreeBSD.org>
# $FreeBSD: head/math/p5-Statistics-Lite/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Statistics-Lite
PORTVERSION=	3.2
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	osa@FreeBSD.org
COMMENT=	The lightweight and functional object-oriented statistics

USES=		dos2unix perl5
USE_PERL5=	configure

.include <bsd.port.mk>
