# Created by: Gerrit Beine (<gerrit@beine-computer.de>)
# $FreeBSD: head/devel/pear-HTML_QuickForm/Makefile 377386 2015-01-19 07:56:19Z vanilla $

PORTNAME=	HTML_QuickForm
PORTVERSION=	3.2.14
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Provide methods for creating, validating, and processing HTML forms

LICENSE=	PHP301

BUILD_DEPENDS=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common
RUN_DEPENDS:=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common

USES=	pear

.include <bsd.port.mk>
