# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/security/pear-Crypt_CBC/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Crypt_CBC
PORTVERSION=	1.0.1
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class to emulate Perl's Crypt::CBC module

USES=	pear

.include <bsd.port.mk>
