# $FreeBSD: head/news/husky-huskylib/Makefile 365427 2014-08-19 22:10:13Z marino $

PORTNAME=	husky-huskylib
CATEGORIES=	news mail

MAINTAINER=	osharoiko@gmail.com
COMMENT=	Husky generic FTN library

INSTALL_TARGET= install install-man
USE_LDCONFIG=	yes

MASTERDIR=	${.CURDIR}/../husky
COMPONENT_SUBDIR=	huskylib

.include <bsd.port.mk>
