# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/net/rubygem-omniauth-facebook/Makefile 390388 2015-06-23 12:22:28Z sunpoet $

PORTNAME=	omniauth-facebook
PORTVERSION=	2.0.1
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Facebook OAuth2 Strategy for OmniAuth

LICENSE=	MIT

RUN_DEPENDS=	rubygem-omniauth-oauth2>=1.2:${PORTSDIR}/net/rubygem-omniauth-oauth2

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
