# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: head/databases/courier-authlib-pgsql/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTREVISION=	1
PKGNAMESUFFIX=	-pgsql

COMMENT=	PostgreSQL support for the Courier authentication library
CATEGORIES=	databases mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

.include "${MASTERDIR}/Makefile"
