# $FreeBSD: head/devel/p5-Module-Pluggable/Makefile 383775 2015-04-11 08:14:25Z mat $

PORTNAME=	Module-Pluggable
PORTVERSION=	5.1
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Automatically give your module the ability to have plugins

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
