# Created by: Dominic Fandrey
# $FreeBSD: head/games/iourbanterror-server/Makefile 394508 2015-08-17 14:20:40Z mat $

PORTNAME=	iourbanterror
PKGNAMESUFFIX=	-server

MAINTAINER=	kamikaze@bsdforen.de
COMMENT=	Urban Terror dedicated server

MASTERDIR=	${.CURDIR}/../${PORTNAME}

IOQ3=		SERVER

.include "${MASTERDIR}/Makefile"
