# Created by: Greg Becker <greg@codeconcepts.com>
# $FreeBSD: head/devel/dits/Makefile 363371 2014-07-29 18:41:15Z adamw $

PORTNAME=	dits
PORTVERSION=	2.3.202
CATEGORIES=	devel
MASTER_SITES=	http://codeconcepts.com/

MAINTAINER=	greg@codeconcepts.com
COMMENT=	Data integrity verifying disk exercising test tool

GNU_CONFIGURE=	yes
USES=		gmake tar:bzip2

PLIST_FILES=	bin/dits \
		man/man1/dits.1.gz

.include <bsd.port.mk>
