# Created by: Steve Wills <swills@rubick>
# $FreeBSD: head/textproc/rubygem-kramdown/Makefile 394222 2015-08-14 14:51:58Z amdmi3 $

PORTNAME=	kramdown
PORTVERSION=	1.8.0
PORTREVISION=	1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Yet-another-markdown-parser but fast, pure Ruby

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
USES=		shebangfix
SHEBANG_FILES=	benchmark/testing.sh benchmark/timing.sh

PLIST_FILES=	bin/kramdown

.include <bsd.port.mk>
