# Created by: Michael Moll <kvedulv@kvedulv.de>
# $FreeBSD: head/sysutils/rubygem-logify/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	logify
PORTVERSION=	0.2.0
CATEGORIES=	sysutils ruby
MASTER_SITES=	RG

MAINTAINER=	mmoll@FreeBSD.org
COMMENT=	Lightweight logging library for Ruby

LICENSE=	APACHE20

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
