# $FreeBSD: head/x11-drivers/xf86-input-void/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-input-void
PORTVERSION=	1.4.0
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org void input driver

XORG_CAT=	driver

.include <bsd.port.mk>
