# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: head/devel/p5-Perl-Unsafe-Signals/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Perl-Unsafe-Signals
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Allow unsafe handling of signals in selected blocks

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
