# $FreeBSD: head/devel/p5-Class-ErrorHandler/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-ErrorHandler
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Base class for error handling

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
