# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/net/pear-Net_IPv6/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_IPv6
DISTVERSION=	1.2.1
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Check and validate IPv6 addresses

USES=	pear

PORTSCOUT=		skipv:1.2.2b,1.2.2b2

.include <bsd.port.mk>
