# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/p5-IO-TieCombine/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	IO-TieCombine
PORTVERSION=	1.004
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl 5 module to produce tied separate but combined variables

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
