# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD: head/www/rubygem-turbolinks-rails41/Makefile 393813 2015-08-09 18:30:17Z swills $

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-coffee-rails41>=4.1.0:${PORTSDIR}/devel/rubygem-coffee-rails41

MASTERDIR=	${.CURDIR}/../rubygem-turbolinks

.include "${MASTERDIR}/Makefile"
