# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/mail/p5-Email-Address/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Email-Address
PORTVERSION=	1.90.5
PORTREVISION=	1
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	RFC 2822 Address Parsing and Creation

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
