# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/pear-Math_Fraction/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Math_Fraction
PORTVERSION=	0.4.1
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Classes that represent and manipulate fractions

USES=	pear

.include <bsd.port.mk>
