# Created by: Bill Fumerola <billf@mu.org>
# $FreeBSD: head/net/wireshark-lite/Makefile 361384 2014-07-09 15:29:37Z tijl $

LITE=		yes
PKGNAMESUFFIX=	-lite

MASTERDIR=	${.CURDIR}/../wireshark
COMMENT=	Powerful network analyzer/capture tool (lite package)

.include "${MASTERDIR}/Makefile"
