# $FreeBSD: head/x11-drivers/xf86-video-neomagic/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-video-neomagic
PORTVERSION=	1.2.8
PORTREVISION=	6
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org neomagic display driver

XORG_CAT=	driver
USE_XORG=	xf86dgaproto

.include <bsd.port.mk>
