# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-HTML_TreeMenu/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_TreeMenu
PORTVERSION=	1.2.2
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Provides an API to create a HTML tree

USES=	pear

.include <bsd.port.mk>
