# Created by: Pakhom Golynga <pakhom706@gmail.com>
# $FreeBSD: head/net-mgmt/zabbix24-proxy/Makefile 372355 2014-11-09 11:06:52Z marino $

PORTNAME=	zabbix24
CATEGORIES=	net-mgmt
PKGNAMESUFFIX=	-proxy

MASTERDIR=	${.CURDIR}/../zabbix24-server

.include "${MASTERDIR}/Makefile"
