# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/textproc/pear-XML_Feed_Parser/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	XML_Feed_Parser
PORTVERSION=	1.0.5
CATEGORIES=	textproc devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Providing a unified API for handling Atom/RSS

USES=		pear
USE_PHP=	tidy dom

.include <bsd.port.mk>
