# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/graphics/pear-Image_Transform/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Image_Transform
PORTVERSION=	0.9.5
CATEGORIES=	graphics www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Standard interface to manipulate images using different libraries

USE_PHP=	gd
USES=	pear

.include <bsd.port.mk>
