# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/www/pear-Services_TinyURL/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_TinyURL
PORTVERSION=	0.1.2
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP interface to TinyURL's API

USES=	pear
USE_PHP=	curl

.include <bsd.port.mk>
