# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/devel/pear-HTML_Template_IT/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_Template_IT
PORTVERSION=	1.3.0
PORTEPOCH=	1
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR Integrated template API

USES=	pear

.include <bsd.port.mk>
