# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/graphics/pear-Image_3D/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Image_3D
PORTVERSION=	0.4.2
CATEGORIES=	graphics www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class allows the rendering of 3 dimensional objects

USE_PHP=	gd
USES=	pear

.include <bsd.port.mk>
