# $FreeBSD: head/x11/xdriinfo/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	xdriinfo
PORTVERSION=	1.0.4
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Query configuration information of DRI drivers

USE_GL=		gl

XORG_CAT=	app
USE_XORG=	x11 glproto
PLIST_FILES=	bin/xdriinfo man/man1/xdriinfo.1.gz

.include <bsd.port.mk>
