# $FreeBSD: head/biology/biococoa/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	biococoa
PORTVERSION=	2.2.2
PORTREVISION=	1
CATEGORIES=	biology gnustep
MASTER_SITES=	http://bioinformatics.org/biococoa/downloads/ DEBIAN/pool/main/b/biococoa.app
DISTNAME=	biococoa-${PORTVERSION}-src
EXTRACT_SUFX=	.tgz

MAINTAINER=	theraven@FreeBSD.org
COMMENT=	Bioinformatics framework

LICENSE=	LGPL21

USES=		gnustep
USE_GNUSTEP=	back build

WRKSRC=		${WRKDIR}/biococoa-${PORTVERSION}

.include <bsd.port.mk>
