# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/net/pear-Net_LDAP2/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_LDAP2
PORTVERSION=	2.0.12
PORTEPOCH=	1
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	OO interface for searching and manipulating LDAP-entries

USES=	pear
USE_PHP=	ldap

.include <bsd.port.mk>
