# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/security/pear-Crypt_RC4/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Crypt_RC4
PORTVERSION=	1.0.3
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR encryption class for RC4 encryption

USES=	pear

.include <bsd.port.mk>
