# Created by: Pakhom Golynga <pakhom706@gmail.com>
# $FreeBSD: head/net-mgmt/zabbix22-proxy/Makefile 351870 2014-04-22 18:31:13Z rene $

PORTNAME=	zabbix22
PKGNAMESUFFIX=	-proxy

MASTERDIR=	${.CURDIR}/../zabbix22-server

.include "${MASTERDIR}/Makefile"
