# $FreeBSD: head/net/elixir-oauth2/Makefile 392569 2015-07-20 14:24:05Z vanilla $

PORTNAME=	oauth2
PORTVERSION=	0.2.0
DISTVERSIONPREFIX=	v
CATEGORIES=	net
PKGNAMEPREFIX=	elixir-

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	OAuth 2.0 library for Elixir

LICENSE=	MIT

MIX_BUILD_DEPS=	devel/elixir-plug \
		devel/elixir-poison \
		www/erlang-hackney \
		www/elixir-httpoison

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	scrogson

.include <bsd.port.mk>
