# Created by: Alexander Logvinov <ports@logvinov.com>
# $FreeBSD: head/devel/rubygem-ruby-ole/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	ruby-ole
PORTVERSION=	1.2.11.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for easy read/write access to OLE compound documents

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/oletool

.include <bsd.port.mk>
