# Created by: Olivier Duchateau <duchateau.olivier@gmail.com>
# $FreeBSD: head/databases/py-pickledb/Makefile 371173 2014-10-19 08:50:17Z mva $

PORTNAME=	pickleDB
PORTVERSION=	0.3
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	duchateau.olivier@gmail.com
COMMENT=	Lightweight, fast, and simple key-value store

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils

PLIST_FILES=	%%PYTHON_SITELIBDIR%%/pickledb.py \
		%%PYTHON_SITELIBDIR%%/pickledb.pyc \
		%%PYTHON_SITELIBDIR%%/pickledb.pyo

.include <bsd.port.mk>
