# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/databases/rubygem-redis-namespace/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	redis-namespace
PORTVERSION=	1.5.2
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby client class for Redis with namespace support

LICENSE=	MIT

RUN_DEPENDS=	rubygem-redis>=3.0.4:${PORTSDIR}/databases/rubygem-redis

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
