# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/devel/pear-Console_Table/Makefile 377384 2015-01-19 07:44:35Z vanilla $

PORTNAME=	Console_Table
PORTVERSION=	1.2.1
CATEGORIES=	devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP class that makes it easy to build console style tables

LICENSE=	BSD3CLAUSE

USES=	pear

.include <bsd.port.mk>
