# Created by: David O'Brien (obrien@NUXI.com)
# $FreeBSD: head/editors/vim-lite/Makefile 374064 2014-12-05 17:45:00Z sunpoet $

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Improved version of the vi editor (lite package)

LITE=		yes
MASTERDIR=	${.CURDIR}/../vim

.include "${MASTERDIR}/Makefile"
