# Created by: antoine@FreeBSD.org
# $FreeBSD: head/devel/py-jdcal/Makefile 366537 2014-08-29 17:28:42Z antoine $

PORTNAME=	jdcal
PORTVERSION=	1.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Module converting between Julian dates and calendar dates

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
