# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD: head/www/p5-Hijk/Makefile 378070 2015-01-28 16:46:04Z tj $

PORTNAME=	Hijk
PORTVERSION=	0.19
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:AVAR
PKGNAMEPREFIX=	p5-

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Fast & minimal low-level HTTP client

LICENSE=	MIT

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
