# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: head/misc/iso-codes/Makefile 394055 2015-08-13 08:50:11Z kwm $

PORTNAME=	iso-codes
PORTVERSION=	3.60
CATEGORIES=	misc
MASTER_SITES=	http://pkg-isocodes.alioth.debian.org/downloads/

MAINTAINER=	kwm@FreeBSD.org
COMMENT=	Lists of the country, language, and currency iso names

LICENSE=	LGPL21

USES=		gettext gmake pathfix tar:xz
GNU_CONFIGURE=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
