# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: head/www/rubygem-ace-rails-ap/Makefile 395071 2015-08-23 00:45:53Z sunpoet $

PORTNAME=	ace-rails-ap
PORTVERSION=	4.0.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ajax.org Cloud9 Editor (Ace) for the Rails 3.1 asset pipeline

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
USES=		shebangfix

SHEBANG_FILES=	update.sh

.include <bsd.port.mk>
