# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/net-mgmt/p5-Xymon-Server/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Xymon-Server
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	net-mgmt
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Xymon Server Interface

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
