# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/security/pear-Crypt_GPG/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Crypt_GPG
PORTVERSION=	1.3.2
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	GNU Privacy Guard (GPG)

USES=	pear
USE_PHP=	posix

.include <bsd.port.mk>
