# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/net/pear-Net_IPv4/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_IPv4
DISTVERSION=	1.3.4
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	IPv4 network calculations and validation

USES=	pear

.include <bsd.port.mk>
