# Created by: Andreas Fehlner (fehlner@gmx.de)
# $FreeBSD: head/french/geonext/Makefile 366749 2014-08-31 12:55:19Z ohauer $

CATEGORIES=	french

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Interactive (dynamic) elementary Geometry Software

RUN_DEPENDS=	geonext>=0:${PORTSDIR}/math/geonext

WITH_LANG=	fr
MASTERDIR=	${.CURDIR}/../../math/geonext

.include "${MASTERDIR}/Makefile"
