# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/www/pear-Services_Yadis/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_Yadis
PORTVERSION=	0.5.2
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Implementation of the Yadis Specification 1.0 protocol for PHP5

USES=	pear

.include <bsd.port.mk>
