# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/devel/pear-Horde_Notification/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Notification
PORTVERSION=	2.0.2
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Notification System

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Util
USE_PHP=	gettext

.include <bsd.port.mk>
