# $FreeBSD: head/editors/libreoffice-am/Makefile 353103 2014-05-06 16:13:01Z jkim $

LO_I18N=	am
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
