# Created by: Palle Girgensohn <girgen@FreeBSD.org>
# $FreeBSD: head/databases/pgbadger/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	pgbadger
PORTVERSION=	6.2
PORTREVISION=	1
CATEGORIES=	databases
MASTER_SITES=	SF/${PORTNAME}/${PORTVERSION}

MAINTAINER=	girgen@FreeBSD.org
COMMENT=	Very competent log analyzer for PostgreSQL

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
