# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: head/mail/courier-authlib-vchkpw/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTREVISION=	1
PKGNAMESUFFIX=	-vchkpw

COMMENT=	Vpopmail/vchkpw support for the Courier authentication library
CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

.include "${MASTERDIR}/Makefile"
