# Created by: Gerrit Beine (<tux@pinguru.net>)
# $FreeBSD: head/devel/pear-HTML_Table/Makefile 369068 2014-09-23 15:15:04Z bapt $

PORTNAME=	HTML_Table
PORTVERSION=	1.8.3
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Makes the design of HTML tables easy, flexible, reusable, and efficient

BUILD_DEPENDS=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common
RUN_DEPENDS=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common

USES=	pear

.include <bsd.port.mk>
