# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/devel/py-oletools/Makefile 369329 2014-09-26 16:03:36Z zi $

PORTNAME=	oletools
PORTVERSION=	0.06
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Tools to analyze security characteristics of MS OLE2 files

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
