# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: head/devel/py-distutils-extra/Makefile 364929 2014-08-15 03:43:54Z sunpoet $

PORTNAME=	distutils-extra
PORTVERSION=	2.38
CATEGORIES=	devel python
MASTER_SITES=	https://launchpad.net/${DISTNAME}/trunk/${PORTVERSION}/+download/ \
		LOCAL/sunpoet
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Add support for i18n, documentation, and icons to distutils

LICENSE=	GPLv2

USE_PYTHON=	autoplist distutils
USES=		python

.include <bsd.port.mk>
