# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/converters/R-cran-jsonlite/Makefile 393767 2015-08-09 08:26:46Z tota $

PORTNAME=	jsonlite
PORTVERSION=	0.9.16
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Robust, High Performance JSON Parser and Generator for R

LICENSE=	MIT

USES=	cran:auto-plist

.include <bsd.port.mk>
