# Created by: Rui Lopes (rgl ruilopes com)
# $FreeBSD: head/devel/rubygem-tzinfo03/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	tzinfo
PORTVERSION=	0.3.44
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	03

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Daylight-savings aware timezone support for Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
