# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: head/multimedia/gstreamer-plugins-vp8/Makefile 388940 2015-06-09 14:25:41Z jbeich $

PORTREVISION=	2
CATEGORIES=	multimedia

COMMENT=	Gstreamer vp8 codec plugin

GST_PLUGIN=	vp8

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
