# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: head/math/R-cran-car/Makefile 382529 2015-03-28 17:40:35Z antoine $

PORTNAME=	car
DISTVERSION=	2.0-25
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Companion to Applied Regression for R

LICENSE=	GPLv2

BROKEN=		Missing dependency

USES=	cran:auto-plist

.include <bsd.port.mk>
