# Created by: ijliao
# $FreeBSD: head/graphics/rubygem-gruff/Makefile 388479 2015-06-03 18:45:39Z sunpoet $

PORTNAME=	gruff
PORTVERSION=	0.6.0
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Beautiful graphing library for Ruby using RMagick

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rmagick>=2.13.4:${PORTSDIR}/graphics/rubygem-rmagick

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
