# $FreeBSD: head/devel/pear-Horde_Icalendar/Makefile 393466 2015-08-03 07:06:14Z mm $

PORTNAME=	Horde_Icalendar
PORTVERSION=	2.1.1
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde iCalendar API

USES=	horde
USE_HORDE_RUN=	Horde_Date \
		Horde_Exception \
		Horde_Mail \
		Horde_Mime \
		Horde_Support \
		Horde_Translation \
		Horde_Util

.include <bsd.port.mk>
