# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/databases/pear-MDB2/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	MDB2
DISTVERSION=	2.5.0b5
CATEGORIES=	databases www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR database abstraction layer

USES=	pear

.include <bsd.port.mk>
