# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Text-Similarity/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Similarity
PORTVERSION=	0.10
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Measure the similarity of text documents

LICENSE=	GPLv2 # (or later)

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
