# Created by: vanilla
# $FreeBSD: head/www/p5-HTML-Strip/Makefile 376870 2015-01-12 18:36:25Z sunpoet $

PORTNAME=	HTML-Strip
PORTVERSION=	2.09
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module for strip HTML tag

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Exception>=0:${PORTSDIR}/devel/p5-Test-Exception

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
