# $FreeBSD: head/devel/mips64-xtoolchain-gcc/Makefile 384399 2015-04-21 01:49:29Z adrian $

PKGNAMEPREFIX=	mips64-
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../powerpc64-xtoolchain-gcc

.include "${MASTERDIR}/Makefile"
