# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD: head/devel/papp/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	papp
PORTVERSION=	0.3.1
CATEGORIES=	devel
MASTER_SITES=	http://acadix.biz/Ports/distfiles/ \
		http://personalpages.tds.net/~jwbacon/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Assembly Preprocessor

LICENSE=	BSD2CLAUSE

.include <bsd.port.mk>
