# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: head/devel/rubygem-ruby-prof/Makefile 388035 2015-05-30 23:11:48Z sunpoet $

PORTNAME=	ruby-prof
PORTVERSION=	0.15.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast profiler for Ruby

LICENSE=	BSD2CLAUSE

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/ruby-prof bin/ruby-prof-check-trace

.include <bsd.port.mk>
