# Created by: Tom McLaughlin <tmclaugh@sdf.lonestar.org>
# $FreeBSD: head/x11-themes/gnome-icons-snow-apple/Makefile 386312 2015-05-14 10:15:04Z mat $

# Port logic gratuitously stolen from x11-themes/kde-icons-noia by
# lioux@.  If it's not defined here and you think it should be, check
# x11-themes/gnome-icons/bsd.gnome-icons.mk for it.

PORTNAME=	snow-apple
PORTVERSION=	20030202
PORTREVISION=	3
CATEGORIES=	x11-themes gnome
MASTER_SITES=	GNOME/teams/art.gnome.org/archive/themes/icon
DISTNAME=	ICON-Snow-Apple

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Snow-Apple Icons for Gnome

RESTRICTED=	${REASON}

WRKSRC=		"${WRKDIR}/Snow-Apple"

.include "${.CURDIR}/../gnome-icons/bsd.gnome-icons.mk"
.include <bsd.port.mk>
