# $FreeBSD: head/japanese/libreoffice/Makefile 371023 2014-10-16 21:14:18Z jkim $

LO_I18N=	ja
LO_HAS_HELPPACK=	yes
CATEGORIES=	japanese editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
