# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/devel/rubygem-kafo_parsers/Makefile 395490 2015-08-28 14:51:59Z mmoll $

PORTNAME=	kafo_parsers
PORTVERSION=	0.0.5
PORTREVISION=	1
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	mmoll@FreeBSD.org
COMMENT=	Parser for puppet modules

LICENSE=	GPLv3

RUN_DEPENDS=	puppet:${PORTSDIR}/sysutils/puppet

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
