# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/www/pear-Services_GeoNames/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_GeoNames
PORTVERSION=	1.0.1
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP5 Interface to the GeoNames Public API

BUILD_DEPENDS=	${PEARDIR}/HTTP/Request2.php:${PORTSDIR}/www/pear-HTTP_Request2
RUN_DEPENDS=	${PEARDIR}/HTTP/Request2.php:${PORTSDIR}/www/pear-HTTP_Request2

USES=	pear

.include <bsd.port.mk>
