# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/www/xpi-prism/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	prism
DISTVERSION=	1.0b2
CATEGORIES=	www
MASTER_SITES=	http://freebsd.unixfreunde.de/sources/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Create Prism applications directly from Firefox

XPI_ID=	refractor@developer.mozilla.org

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
