# Created by: Neil Booth
# $FreeBSD: head/net/py-pysocks/Makefile 381922 2015-03-22 14:59:10Z sunpoet $

PORTNAME=	pysocks
PORTVERSION=	1.5.0
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	PySocks-${PORTVERSION}

MAINTAINER=	kyuupichan@gmail.com
COMMENT=	Python SOCKS module

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
