# Created by: Nick Hilliard <nick@foobar.org>
# $FreeBSD: head/devel/pear-Structures_DataGrid_Renderer_XUL/Makefile 369068 2014-09-23 15:15:04Z bapt $

PORTNAME=	Structures_DataGrid_Renderer_XUL
PORTVERSION=	0.1.3
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	XUL Renderer for pear-Structures_DataGrid

RUN_DEPENDS=	${PEARDIR}/Structures/DataGrid.php:${PORTSDIR}/devel/pear-Structures_DataGrid \
		${PEARDIR}/XML/Util.php:${PORTSDIR}/devel/pear-XML_Util

USES=	pear

.include <bsd.port.mk>
