# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/net/pear-XML_RPC/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	XML_RPC
PORTVERSION=	1.5.5
CATEGORIES=	net devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP implementation of the XML-RPC protocol

USE_PHP=	xml
USES=	pear

.include <bsd.port.mk>
