# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/pear-PHP_ParserGenerator/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	PHP_ParserGenerator
PORTVERSION=	0.1.7
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Convert files from lemon parser to php5

USES=	pear

.include <bsd.port.mk>
