# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/shells/pear-PHP_Shell/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	PHP_Shell
PORTVERSION=	0.3.2
CATEGORIES=	shells www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Interactive PHP Shell

USE_PHP=	pcre tokenizer readline

USES=	pear

.include <bsd.port.mk>
