# Created by: Gerrit Beine (<gerrit.beine@gmx.de>)
# $FreeBSD: head/graphics/pear-Image_GraphViz/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Image_GraphViz
PORTVERSION=	1.3.0
CATEGORIES=	graphics www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Interface to AT&T's GraphViz tools

RUN_DEPENDS=	${LOCALBASE}/bin/dot:${PORTSDIR}/graphics/graphviz

USES=	pear

.include <bsd.port.mk>
