# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/mail/pear-Mail_mimeDecode/Makefile 374153 2014-12-06 21:00:41Z feld $

PORTNAME=	Mail_mimeDecode
PORTVERSION=	1.5.5
CATEGORIES=	mail www pear
DISTNAME=	Mail_mimeDecode-${PORTVERSION}

MAINTAINER=	joehorn@gmail.com
COMMENT=	Provides a class to decode mime messages

BUILD_DEPENDS=	${PEARDIR}/Mail/mime.php:${PORTSDIR}/mail/pear-Mail_Mime
RUN_DEPENDS=	${PEARDIR}/Mail/mime.php:${PORTSDIR}/mail/pear-Mail_Mime

LICENSE=	BSD3CLAUSE

USES=	pear

.include <bsd.port.mk>
