# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/textproc/py-texttable/Makefile 391368 2015-07-05 18:18:25Z rm $

PORTNAME=	texttable
PORTVERSION=	0.8.3
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP \
		http://foutaise.org/code/texttable/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Module for creating simple ASCII tables

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
