# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/misc/pear-Text_Figlet/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Text_Figlet
PORTVERSION=	1.0.2
CATEGORIES=	misc www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Render text using FIGlet fonts

USES=	pear

.include <bsd.port.mk>
