# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-Var_Dump/Makefile 380204 2015-03-01 15:08:17Z amdmi3 $

PORTNAME=	Var_Dump
PORTVERSION=	1.0.4
PORTREVISION=	1
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Provides methods for dumping structured information about a variable

LICENSE=	PHP30

RUN_DEPENDS=	bash:${PORTSDIR}/shells/bash

USES=		pear shebangfix
SHEBANG_FILES=	scripts/gen_php_doc.sh

.include <bsd.port.mk>
