# Created by: Shin-ya MURAKAMI <murashin@gfd-dennou.org>
# $FreeBSD: head/devel/rubygem-slop/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	slop
PORTVERSION=	3.6.0
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple DSL for gathering options and parsing the command line

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
