# $FreeBSD: head/devel/rubygem-rufus-scheduler/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	rufus-scheduler
PORTVERSION=	3.1.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	robak@FreeBSD.org
COMMENT=	Ruby job scheduler for at, cron and others

LICENSE=	MIT

RUN_DEPENDS=	rubygem-tzinfo>=0:${PORTSDIR}/devel/rubygem-tzinfo

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
