# $FreeBSD: head/irc/rubygem-cinch/Makefile 391652 2015-07-09 15:44:39Z sunpoet $

PORTNAME=	cinch
PORTVERSION=	2.2.6
CATEGORIES=	irc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	IRC Bot Building Framework

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
