# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/pear-PHP_CodeSniffer/Makefile 392875 2015-07-25 11:38:14Z netchild $

PORTNAME=	PHP_CodeSniffer
PORTVERSION=	2.3.3
PORTREVISION=	1
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP Script Tokenises and Sniffs PHP and JavaScript code

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USES=		pear
USE_PHP=	simplexml tokenizer

.include <bsd.port.mk>
