# $FreeBSD: head/x11/xgamma/Makefile 364347 2014-08-08 08:42:44Z olgeni $

PORTNAME=	xgamma
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Gamma correction through the X server

XORG_CAT=	app
USE_XORG=	x11 xxf86vm

PLIST_FILES=	bin/xgamma man/man1/xgamma.1.gz

.include <bsd.port.mk>
