# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: head/sysutils/rubygem-god/Makefile 382144 2015-03-24 18:00:31Z sunpoet $

PORTNAME=	god
PORTVERSION=	0.13.6
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Monitoring framework written in Ruby

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/god

.include <bsd.port.mk>
