# Created by: Carlo Strub
# $FreeBSD: head/devel/py-testtools/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	testtools
PORTVERSION=	0.9.35
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	http://launchpadlibrarian.net/164010578/ \
		http://www.c-s.li/ports/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Extensions to the Python library's unit testing framework

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}extras>=0.0.3:${PORTSDIR}/devel/py-extras

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
