# $FreeBSD: head/devel/elixir-paratize/Makefile 394641 2015-08-18 19:20:22Z olgeni $

PORTNAME=	elixir-paratize
PORTVERSION=	2.1.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Parallel processing facilities for Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	seantanly

ELIXIR_APP_NAME=paratize
MIX_REWRITE=	yes

.include <bsd.port.mk>
