# Created by: Anish Mistry <amistry@am-productions.biz>
# $FreeBSD: head/print/pear-File_PDF/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	File_PDF
PORTVERSION=	0.3.3
CATEGORIES=	print pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class to generate PDFs

USES=	pear

.include <bsd.port.mk>
