# $FreeBSD: head/x11-drivers/xf86-input-keyboard/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-input-keyboard
PORTVERSION=	1.8.0
PORTREVISION=	7
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org keyboard input driver

XORG_CAT=	driver
USE_XORG=	kbproto

.include <bsd.port.mk>
