# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/security/pear-Horde_Perms/Makefile 393466 2015-08-03 07:06:14Z mm $

PORTNAME=	Horde_Perms
PORTVERSION=	2.1.5
CATEGORIES=	security www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Permissions System

USES=	horde
USE_HORDE_RUN=	Horde_Db \
		Horde_Exception \
		Horde_Group \
		Horde_Util \
		Horde_Translation

.include <bsd.port.mk>
