# Created by: bruno
# $FreeBSD: head/french/alphabet_sounds_fr/Makefile 383288 2015-04-05 11:23:53Z antoine $

PORTNAME=	alphabet_sounds_fr
PORTVERSION=	0.3
PORTREVISION=	14
CATEGORIES=	french games
MASTER_SITES=	SF/childsplay/OldFiles
DISTNAME=	alphabet_sounds_fr

MAINTAINER=	bruno@tinkerbox.org
COMMENT=	Educative games for children. Alphabet sounds package (french)

BROKEN=		No public distfiles

RUN_DEPENDS=	${LOCALBASE}/bin/childsplay:${PORTSDIR}/games/childsplay

USES=		python

.include <bsd.port.mk>
