# $FreeBSD: head/x11-drivers/xf86-video-s3/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-video-s3
PORTVERSION=	0.6.5
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org s3 display driver

XORG_CAT=	driver

.include <bsd.port.mk>
