# Created by: Gerrit Beine (<gerrit@beine-computer.de>)
# $FreeBSD: head/devel/pear-PHPDoc/Makefile 369068 2014-09-23 15:15:04Z bapt $

PORTNAME=	PHPDoc
PORTVERSION=	0.1.0
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tool to generate documentation from the source

USES=	pear

.include <bsd.port.mk>
