# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/devel/rubygem-fast_gettext/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	fast_gettext
PORTVERSION=	0.9.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast, memory-efficient and threadsafe GetText for Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
