# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/math/p5-Number-Uncertainty/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Number-Uncertainty
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Object-orientated uncertainty object

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
