# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py-isodate/Makefile 364929 2014-08-15 03:43:54Z sunpoet $

PORTNAME=	isodate
PORTVERSION=	0.5.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	ISO 8601 date/time/duration parser and formater

LICENSE=	BSD3CLAUSE

USE_PYTHON=	autoplist distutils
USES=		python

.include <bsd.port.mk>
