# $FreeBSD: head/textproc/elixir-sweet_xml/Makefile 394603 2015-08-18 15:19:32Z olgeni $

PORTNAME=	sweet_xml
PORTVERSION=	0.3.0
CATEGORIES=	textproc
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Wrapper around xmerl application for Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	gniquil

.include <bsd.port.mk>
