# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/dns/rubygem-public_suffix/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	public_suffix
PORTVERSION=	1.5.1
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby domain name parser based on the Public Suffix List

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
