# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: head/math/pecl-stats/Makefile 379768 2015-02-24 08:59:26Z vanilla $

PORTNAME=	stats
PORTVERSION=	1.0.3
CATEGORIES=	math textproc pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PECL extension which with routines for statistical computation

LICENSE=	PHP30

USES=		tar:tgz
USE_PHP=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
