# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: head/textproc/p5-Unicode-Normalize/Makefile 391753 2015-07-11 15:28:09Z sunpoet $

PORTNAME=	Unicode-Normalize
PORTVERSION=	1.19
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Unicode Normalization Forms

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
