# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: head/www/py-feedfinder/Makefile 382756 2015-03-30 21:47:11Z bapt $

PORTNAME=	feedfinder
PORTVERSION=	1.3.7.1
CATEGORIES=	www python
MASTER_SITES=	CENKES
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Ultra-liberal feed finder

BROKEN=		No public distfiles

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
