# $FreeBSD: head/databases/rubygem-arel-helpers/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	arel-helpers
PORTVERSION=	2.1.0
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Helpers to construct database queries with ActiveRecord and Arel

LICENSE=	MIT

RUN_DEPENDS=	rubygem-activerecord>=3.1.0:${PORTSDIR}/databases/rubygem-activerecord

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
