# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/devel/pear-VersionControl_Git/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	VersionControl_Git
PORTVERSION=	0.4.4
CATEGORIES=	devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	OO interface to handle Git repository

USES=	pear

.include <bsd.port.mk>
