# $FreeBSD: head/devel/rubygem-gitlab_meta/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	gitlab_meta
PORTVERSION=	7.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	GitLab meta gem

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
USES=		cpe

CPE_PRODUCT=	gitlab
CPE_VENDOR=	gitlab

.include <bsd.port.mk>
