# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/devel/pear-XML_Util/Makefile 384572 2015-04-23 13:27:32Z vanilla $

PORTNAME=	XML_Util
PORTVERSION=	1.3.0
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR XML utility class

LICENSE=	BSD2CLAUSE

USES=		pear

.include <bsd.port.mk>
