# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php55-mcrypt/Makefile 389655 2015-06-14 20:23:09Z ale $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-mcrypt

.include "${MASTERDIR}/Makefile"
