# $FreeBSD: head/devel/elixir-excoveralls/Makefile 393146 2015-07-29 09:56:46Z vanilla $

PORTNAME=	excoveralls
PORTVERSION=	0.3.11
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	Coverage Reports for Elixir

LICENSE=	APACHE20

MIX_BUILD_DEPS=	devel/elixir-exjsx \
		www/erlang-hackney

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	parroty

.include <bsd.port.mk>
