# Created by: Carlo Strub
# $FreeBSD: head/security/py-stem/Makefile 389650 2015-06-14 19:56:48Z cs $

PORTNAME=	stem
PORTVERSION=	1.4.1
PORTREVISION=	1
CATEGORIES=	security net python
MASTER_SITES=	http://www.c-s.li/ports/ \
		CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Python controller library for Tor

LICENSE=	LGPL3

USES=		python tar:bzip2
USE_PYTHON=	distutils

.include <bsd.port.mk>
