# Created by: Thierry Thomas (<thierry@FreeBSD.org>)
# $FreeBSD: head/devel/pear-VFS/Makefile 369068 2014-09-23 15:15:04Z bapt $

PORTNAME=	VFS
PORTVERSION=	0.3.0
CATEGORIES=	devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR Virtual File System API

BUILD_DEPENDS=	${PEARDIR}/Log/null.php:${PORTSDIR}/sysutils/pear-Log
RUN_DEPENDS=	${PEARDIR}/Log/null.php:${PORTSDIR}/sysutils/pear-Log

USE_PHP=	gettext
USES=	pear

.include <bsd.port.mk>
