# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/graphics/php55-gd/Makefile 389655 2015-06-14 20:23:09Z ale $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-gd

.include "${MASTERDIR}/Makefile"
