# $FreeBSD: head/x11-drivers/xf86-video-glint/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-video-glint
PORTVERSION=	1.2.8
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org glint display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto xf86dgaproto glproto

.include <bsd.port.mk>
