# Created by: Sergey Skvortsov <skv@FreeBSD.org>
# $FreeBSD: head/devel/p5-Event/Makefile 380185 2015-03-01 14:32:22Z sunpoet $

PORTNAME=	Event
PORTVERSION=	1.24
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generic Perl Event Loop

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
