#!/bin/sh
#
# $FreeBSD: releng/10.2/etc/rc.d/NETWORKING 279499 2015-03-01 21:24:19Z ngie $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netoptions routing ppp ipfw stf faith
# REQUIRE: defaultroute routed mrouted route6d mroute6d resolv bridge
# REQUIRE: static_arp static_ndp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
