# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/www/pear-HTTP_Session2/Makefile 375166 2014-12-21 16:09:04Z feld $

PORTNAME=	HTTP_Session2
PORTVERSION=	0.7.3
CATEGORIES=	www devel pear

MAINTAINER=	joehorn@gmail.com
COMMENT=	PHP5 Session Handler

LICENSE=	BSD3CLAUSE

USES=		dos2unix pear

.include <bsd.port.mk>
