# Created by: Valerio Daelli <valerio.daelli@gmail.com>
# $FreeBSD: head/security/ossec-hids-client/Makefile 389271 2015-06-12 14:13:29Z brd $

PORTREVISION=	0
COMMENT=	The client port of ossec-hids

CLIENT_ONLY=	yes

MASTERDIR=	${.CURDIR}/../ossec-hids-server

PLIST=	pkg-plist.client

.include "${MASTERDIR}/Makefile"
