# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/audio/gstreamer-plugins-pulse/Makefile 352119 2014-04-25 12:46:45Z bapt $

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	GStreamer plugin for pulseaudio

GST_PLUGIN=	pulse

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
