# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/math/pear-Math_Combinatorics/Makefile 369092 2014-09-23 16:45:35Z bapt $

PORTNAME=	Math_Combinatorics
PORTVERSION=	1.0.0
PORTEPOCH=	1
CATEGORIES=	math pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Package that produces combinations and permutations

USES=	pear

.include <bsd.port.mk>
