# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/math/py-mathdom/Makefile 371328 2014-10-21 16:54:54Z mva $

PORTNAME=	mathdom
PORTVERSION=	0.8
PORTREVISION=	1
CATEGORIES=	math python
MASTER_SITES=	CHEESESHOP/source/m/${PORTNAME}/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wenheping@gmail.com
COMMENT=	Content MathML in Python

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}lxml>0:${PORTSDIR}/devel/py-lxml

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
