# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/net/pear-Net_UserAgent_Detect/Makefile 374502 2014-12-10 23:55:29Z feld $

PORTNAME=	Net_UserAgent_Detect
PORTVERSION=	2.5.2
PORTREVISION=	1
CATEGORIES=	net www pear

MAINTAINER=	joehorn@gmail.com
COMMENT=	PEAR class that determines the Web browser, version, and platform

LICENSE=	PHP202

USES=	pear

.include <bsd.port.mk>
