# Created by: Dryice Liu <dryice@FreeBSD.org>
# $FreeBSD: head/www/py-beaker/Makefile 370033 2014-10-05 01:15:55Z wen $

PORTNAME=	beaker
PORTVERSION=	1.6.4
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Beaker-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Session and Caching library with WSGI Middleware

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
