# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-ruby-filemagic/Makefile 393349 2015-07-31 16:26:50Z sunpoet $

PORTNAME=	ruby-filemagic
PORTVERSION=	0.7.0
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby binding to libmagic(3)

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
