# Created by: Andrei V. Shetuhin <reki@reki.ru>
# $FreeBSD: head/converters/p5-String-SetUTF8/Makefile 383312 2015-04-05 18:21:09Z bapt $

PORTNAME=	String-SetUTF8
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	reki@reki.ru
COMMENT=	Perl module to manipulate internal UTF-8 flag on strings

BROKEN=		Unfetchable

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
