# $FreeBSD: head/graphics/digikam-kde4-doc/Makefile 378020 2015-01-27 21:04:30Z makc $

PORTNAME=	digikam-doc
PORTVERSION=	${DIGIKAM_VER}
CATEGORIES=	graphics kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Documentation for digiKam, showFoto, and Kipi-plugins

CONFLICTS_INSTALL=	digikam-2.* kipi-plugins-2.* 

WRKSRC=		${WRKDIR}/${DISTNAME}/doc

.include "${.CURDIR}/../digikam-kde4/Makefile.common"
.include <bsd.port.mk>
