# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/www/pear-Services_SharedBook/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_SharedBook
PORTVERSION=	0.2.6
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP wrapper for SharedBook Open API

BUILD_DEPENDS=	${PEARDIR}/HTTP/Client.php:${PORTSDIR}/www/pear-HTTP_Client
RUN_DEPENDS=	${PEARDIR}/HTTP/Client.php:${PORTSDIR}/www/pear-HTTP_Client

USES=	pear

.include <bsd.port.mk>
