# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD: head/devel/rubygem-coffee-rails41/Makefile 393800 2015-08-09 16:09:25Z swills $

PKGNAMESUFFIX=	41

RUN_DEPENDS=	rubygem-coffee-script>=2.2.0:${PORTSDIR}/devel/rubygem-coffee-script \
		rubygem-railties41>=4.1.12:${PORTSDIR}/www/rubygem-railties41

MASTERDIR=	${.CURDIR}/../rubygem-coffee-rails4

.include "${MASTERDIR}/Makefile"
