# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-pry-rails/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	pry-rails
PORTVERSION=	0.3.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Use Pry as your rails console

LICENSE=	MIT

RUN_DEPENDS=	rubygem-pry>=0.9.10:${PORTSDIR}/devel/rubygem-pry

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
