# Created by: Thierry Thomas (<thierry@FreeBSD.org>)
# $FreeBSD: head/sysutils/pear-Cache/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Cache
PORTVERSION=	1.5.6
PORTREVISION=	1
CATEGORIES=	sysutils www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR framework for caching of arbitrary data

BUILD_DEPENDS=	${PEARDIR}/HTTP/Request.php:${PORTSDIR}/www/pear-HTTP_Request
RUN_DEPENDS=	${PEARDIR}/HTTP/Request.php:${PORTSDIR}/www/pear-HTTP_Request

USES=	pear

.include <bsd.port.mk>
