# $FreeBSD: head/x11-drivers/xf86-input-fpit/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-input-fpit
PORTVERSION=	1.4.0
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org fpit input driver

XORG_CAT=	driver
USE_XORG=	xrandr

.include <bsd.port.mk>
