# Created by: Foxfair Hu <foxfair@FreeBSD.org>
# $FreeBSD: head/chinese/tintin++/Makefile 383406 2015-04-06 07:06:28Z sunpoet $

CATEGORIES=	chinese

MAINTAINER=	sunpoet@FreeBSD.org

LICENSE=	GPLv2

MASTERDIR=	${.CURDIR}/../../net/tintin++

OPTIONS_SLAVE=	BIG5

.include "${MASTERDIR}/Makefile"
