# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/textproc/rubygem-linguistics/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	linguistics
PORTVERSION=	2.0.4
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Framework for extending Ruby objects with linguistic methods

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	rubygem-loggability>=0.11:${PORTSDIR}/textproc/rubygem-loggability

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
