# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/misc/rubygem-mime-types/Makefile 389421 2015-06-13 13:56:16Z sunpoet $

PORTNAME=	mime-types
PORTVERSION=	2.6.1
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby gem which provides a mailcap-like MIME Content-Type lookup

LICENSE=	ART20 GPLv2 GPLv3 MIT
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
