# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: head/devel/p5-PerlX-Maybe/Makefile 379934 2015-02-25 18:23:31Z adamw $

PORTNAME=	PerlX-Maybe
PORTVERSION=	1.001
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:TOBYINK
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Return a pair only if they are both defined

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
