# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: head/dns/p5-Net-Domain-TLD/Makefile 383447 2015-04-06 16:22:51Z pi $

PORTNAME=	Net-Domain-TLD
PORTVERSION=	1.73
CATEGORIES=	dns perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	vivek@khera.org
COMMENT=	Look up and validate TLDs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
