# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXrandr/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libXrandr
PORTVERSION=	1.4.2
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Resize and Rotate extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 randrproto:both xext xextproto xrender renderproto xproto:both
USES+=	cpe
CPE_PRODUCT=	libxrandr
CPE_VENDOR=	x

.include <bsd.port.mk>
