# Created by: Bill Fumerola <billf@mu.org>
# $FreeBSD: head/net/tshark-lite/Makefile 361440 2014-07-10 12:13:11Z olgeni $

LITE=		yes
PKGNAMESUFFIX=	-lite

MASTERDIR=	${.CURDIR}/../tshark
COMMENT=	Powerful network analyzer/capture tool (lite package)

.include "${MASTERDIR}/Makefile"
