# Created by: Wen heping <wenheping@gmail.com>)
# $FreeBSD: head/www/pear-Services_Facebook/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_Facebook
PORTVERSION=	0.2.14
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP interface to Facebook's API

BUILD_DEPENDS=	${PEARDIR}/Validate.php:${PORTSDIR}/devel/pear-Validate
RUN_DEPENDS=	${PEARDIR}/Validate.php:${PORTSDIR}/devel/pear-Validate

USES=	pear
USE_PHP=	curl

.include <bsd.port.mk>
