# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: head/www/rubygem-dropzonejs-rails/Makefile 390863 2015-06-28 17:58:23Z sunpoet $

PORTNAME=	dropzonejs-rails
PORTVERSION=	0.7.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	JS File upload by Matias Meno

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rails4>=4.1.4:${PORTSDIR}/www/rubygem-rails4

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
