# Created by: olevole@olevole.ru
# $FreeBSD: head/deskutils/py-spice-gtk/Makefile 378739 2015-02-09 16:21:59Z jgh $

COMMENT=	Python bindings for SPICE remote desktop servers
MASTERDIR=	${.CURDIR}/../spice-gtk

CONFLICTS=	spice-gtk-[0-9]*
SPICE_SLAVE=	yes

.include "${MASTERDIR}/Makefile"
