# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@sunpoet.net>
# $FreeBSD: head/devel/p5-Module-Version/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Module-Version
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Get module versions

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
