# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD: head/sysutils/py-plumbum/Makefile 371454 2014-10-24 16:56:10Z mva $

PORTNAME=	plumbum
PORTVERSION=	1.4.2
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Shell combinators and more for python

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
