# Created by: Alexander Logvinov <avl@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-jruby-jars/Makefile 395012 2015-08-22 04:25:09Z sunpoet $

PORTNAME=	jruby-jars
PORTVERSION=	1.7.22
CATEGORIES=	devel rubygems java
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	JAR files from the JRuby distribution

LICENSE=	EPL GPLv2 LGPL21
LICENSE_COMB=	dual

USE_JAVA=	yes
NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
