# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-sass32/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	sass
PORTVERSION=	3.2.19
CATEGORIES=	textproc ruby
MASTER_SITES=	RG
PKGNAMESUFFIX=	32

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sass is an extension of CSS3

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	ignore

.include <bsd.port.mk>
