# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: head/x11-toolkits/py-wxPython28-unicode/Makefile 360789 2014-07-05 18:22:32Z wg $

WITH_WXPYTHON_UNICODE=	yes

MASTERDIR=	${.CURDIR}/../py-wxPython28

.include "${MASTERDIR}/Makefile"
