# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: head/net/p5-Net-Ping-External/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-Ping-External
PORTVERSION=	0.13
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	Perl cross-platform interface to ICMP "ping" utilities

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5 zip
USE_PERL5=	configure

.include <bsd.port.mk>
