# Created by: fjoe@FreeBSD.org
# $FreeBSD: head/x11-toolkits/wxgtk28-unicode/Makefile 347864 2014-03-11 07:13:06Z miwi $

MAINTAINER=	fjoe@FreeBSD.org
COMMENT=	The wxWidgets GUI toolkit (Unicode)

WXGTK_FLAVOR=	gtk2-unicode
MASTERDIR=	${.CURDIR}/../wxgtk28

.include "${MASTERDIR}/Makefile"
