# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-async/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	async
PORTVERSION=	0.6.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Framework to process interdependent tasks in a pool of workers

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
