# $FreeBSD: head/devel/gwenhywfar-fox16/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTREVISION=	6
PKGNAMESUFFIX=	-${SLAVEPORT}

MAINTAINER=	jhale@FreeBSD.org
COMMENT=	Gwenhywfar FOX-1.6 support library

MASTERDIR=	${.CURDIR}/../../devel/gwenhywfar
SLAVEPORT=	fox16
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
