# $FreeBSD: head/devel/elixir-hex/Makefile 392392 2015-07-17 17:57:45Z olgeni $

PORTNAME=	hex
PORTVERSION=	0.8.3
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Package manager for the Erlang VM

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	hexpm

.include <bsd.port.mk>
