# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11-fonts/libfontenc/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libfontenc
PORTVERSION=	1.1.2
PORTREVISION=	3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The fontenc Library

XORG_CAT=	lib
USE_XORG=	xproto

.include <bsd.port.mk>
