# $FreeBSD: head/vietnamese/libreoffice/Makefile 371023 2014-10-16 21:14:18Z jkim $

LO_I18N=	vi
LO_HAS_HELPPACK=	yes
CATEGORIES=	vietnamese editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
