# $FreeBSD: head/devel/rubygem-redis-store/Makefile 392414 2015-07-18 11:13:41Z sunpoet $

PORTNAME=	redis-store
PORTVERSION=	1.1.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Namespaced Redis stores for Ruby web frameworks

LICENSE=	MIT

RUN_DEPENDS=	rubygem-redis>=2.2:${PORTSDIR}/databases/rubygem-redis

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
