# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/sysutils/pear-File_Gettext/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	File_Gettext
PORTVERSION=	0.4.2
CATEGORIES=	sysutils devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR GNU Gettext file parser

USES=	pear
USE_PHP=	yes

.include <bsd.port.mk>
