# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: head/devel/rubygem-sequel/Makefile 393418 2015-08-02 06:43:00Z sunpoet $

PORTNAME=	sequel
PORTVERSION=	4.25.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Database Toolkit for Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/sequel

.include <bsd.port.mk>
