# Created by: Gerrit Beine (<tux@pinguru.net>)
# $FreeBSD: head/net/pear-Net_Server/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_Server
PORTVERSION=	1.0.3
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Generic server class

USES=	pear
USE_PHP=	sockets pcntl

.include <bsd.port.mk>
