# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-zope.event/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	zope.event
PORTVERSION=	3.5.2
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Very basic event publishing system

LICENSE=	ZPL21

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
