# $FreeBSD: head/devel/rubygem-aws-sdk-resources/Makefile 391800 2015-07-12 16:08:11Z sunpoet $

PORTNAME=	aws-sdk-resources
PORTVERSION=	2.0.48
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	AWS SDK for Ruby Resources

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-aws-sdk-core>=${PORTVERSION}:${PORTSDIR}/devel/rubygem-aws-sdk-core

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
