# $FreeBSD: head/devel/rubygem-georuby/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	GeoRuby
PORTVERSION=	1.3.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Holder for data returned from PostGIS and the Spatial Extensions of MySql	

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
