# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php56-filter/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-filter

.include "${MASTERDIR}/Makefile"
