# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/pear-PHP_Parser/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	PHP_Parser
PORTVERSION=	0.2.2
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP Grammar Parser

USES=	pear

.include <bsd.port.mk>
