# $FreeBSD: head/news/husky/Makefile 365427 2014-08-19 22:10:13Z marino $

PORTNAME=	husky

COMMENT=	Husky full featured highly portable FTN Tosser

RUN_DEPENDS=	hpt:${PORTSDIR}/news/husky-hpt \
		htick:${PORTSDIR}/news/husky-htick

MASTERDIR=	${.CURDIR}

NO_BUILD=	yes
NO_INSTALL=	yes

.include <bsd.port.mk>
