# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/sysutils/pear-Cache_Lite/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Cache_Lite
PORTVERSION=	1.7.16
PORTEPOCH=	1
CATEGORIES=	sysutils www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR fast and safe little cache system

USES=	pear

.include <bsd.port.mk>
