# Created by: will
# $FreeBSD: head/devel/p5-Proc-Daemon/Makefile 389629 2015-06-14 12:49:57Z lth $

PORTNAME=	Proc-Daemon
PORTVERSION=	0.19
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Perl module that provides a method to daemonify a Perl script

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Proc-ProcessTable>0:${PORTSDIR}/devel/p5-Proc-ProcessTable

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
