# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php5-interbase/Makefile 343435 2014-02-09 08:39:00Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-interbase

.include "${MASTERDIR}/Makefile"
