# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: head/devel/p5-Time-Warp/Makefile 376341 2015-01-05 18:51:06Z lth $

PORTNAME=	Time-Warp
PORTVERSION=	0.51
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Control over the flow of time

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
