# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-Console_Getargs/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Console_Getargs
PORTVERSION=	1.3.5
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR command-line arguments parser

USES=	pear

.include <bsd.port.mk>
