# Created by: Pawel Pekala <c0rn@o2.pl>
# $FreeBSD: head/mail/claws-mail-clamd/Makefile 355574 2014-05-27 21:11:52Z pawel $

PORTNAME=	clamd
PORTREVISION=	0

COMMENT=	ClamAV based antivirus plugin for Claws Mail

RUN_DEPENDS=	clamd:${PORTSDIR}/security/clamav

CLAWS_PLUGINS_BUILD=	clamd

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
