# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/devel/nuitka/Makefile 395176 2015-08-24 16:04:09Z danfe $

PORTNAME=	nuitka
PORTVERSION=	0.5.13.8
CATEGORIES=	devel python
MASTER_SITES=	http://nuitka.net/releases/
DISTNAME=	Nuitka-${PORTVERSION}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Compatible and efficient Python compiler

LICENSE=	APACHE20

USES=		python tar:bzip2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
