# Created by: Christoph Moench-Tegeder <cmt@burggraben.net>
# $FreeBSD: head/astro/garmindev/Makefile 340341 2014-01-19 18:57:19Z bapt $

PORTNAME=	garmindev
PORTVERSION=	0.3.4
CATEGORIES=	astro
MASTER_SITES=	SF/qlandkartegt/${PORTNAME}/Garmin%20Device%20Driver%20${PORTVERSION}

MAINTAINER=	cmt@burggraben.net
COMMENT=	Drivers for using Garmin GPS units with QlandkarteGT

LICENSE=	GPLv2

USES=		cmake

.include <bsd.port.mk>
