# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11-fonts/fontsproto/Makefile 362402 2014-07-21 06:38:49Z bapt $

PORTNAME=	fontsproto
PORTVERSION=	2.1.2
PORTEPOCH=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fonts extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
