# Created by: Foxfair Hu <foxfair@FreeBSD.org>
# $FreeBSD: head/x11/libXrender/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libXrender
PORTVERSION=	0.9.8
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Render extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 renderproto:both xproto:both

.include <bsd.port.mk>
