# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/textproc/pear-File_MARC/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	File_MARC
PORTVERSION=	1.1.1
CATEGORIES=	textproc pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Parse, modify, and create MARC records

USES=	pear

.include <bsd.port.mk>
