# Created by: Martin Wilke (miwi@FreeBSD.org)
# $FreeBSD: head/devel/pear-Testing_Selenium/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Testing_Selenium
PORTVERSION=	0.4.4
CATEGORIES=	devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR Binding - Once more unto the breach

USES=	pear

.include <bsd.port.mk>
