# Created by: Yoshifumi Watanabe <mwatts@edu1.tokyo-med.ac.jp>
# $FreeBSD: head/sysutils/bkpupsd/Makefile 362126 2014-07-17 08:57:51Z olgeni $

PORTNAME=	bkpupsd
PORTVERSION=	1.0a
CATEGORIES=	sysutils
MASTER_SITES=	http://ftp.knit.kagoshima-u.ac.jp/pub/Unix/bkpupsd/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple UPS daemon for APC BK Pro(TM)

.include <bsd.port.mk>
