# $FreeBSD: head/devel/rubygem-font-awesome-rails-rails4/Makefile 393347 2015-07-31 16:26:39Z sunpoet $

PORTNAME=	font-awesome-rails
PORTVERSION=	4.4.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails4

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides the Font-Awesome web fonts and stylesheets as a Rails engine

LICENSE=	MIT OFL11
LICENSE_COMB=	dual

RUN_DEPENDS=	rubygem-railties4>=3.2:${PORTSDIR}/www/rubygem-railties4

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
