# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/textproc/py-pss/Makefile 377235 2015-01-17 16:11:43Z vanilla $

PORTNAME=	pss
PORTVERSION=	1.39
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tool for grepping through source code

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
