# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: head/www/pear-HTTP_WebDAV_Client/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTTP_WebDAV_Client
PORTVERSION=	1.0.2
CATEGORIES=	www devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	WebDAV Stream Wrapper Class

BUILD_DEPENDS=	${PEARDIR}/HTTP/Request.php:${PORTSDIR}/www/pear-HTTP_Request
RUN_DEPENDS:=	${PEARDIR}/HTTP/Request.php:${PORTSDIR}/www/pear-HTTP_Request

USES=	pear

.include <bsd.port.mk>
