# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/devel/pear-HTML_Template_PHPLIB/Makefile 369068 2014-09-23 15:15:04Z bapt $

PORTNAME=	HTML_Template_PHPLIB
PORTVERSION=	1.5.2
PORTREVISION=	1
CATEGORIES=	devel www pear

MAINTAINER=	joehorn@gmail.com
COMMENT=	PEAR template API ported from PHPLIB

LICENSE=	LGPL3

USES=	pear

.include <bsd.port.mk>
