# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/www/pear-Services_urlTea/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_urlTea
PORTVERSION=	0.1.0
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP interface to urlTea's API

USES=	pear
USE_PHP=	curl

.include <bsd.port.mk>
