# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: head/textproc/py-pygtail/Makefile 366499 2014-08-29 10:48:28Z demon $

PORTNAME=	pygtail
PORTVERSION=	0.4.0
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Python module which reads log file lines that have not been read

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
