# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: head/www/pear-HTTP_WebDAV_Server/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTTP_WebDAV_Server
PORTVERSION=	1.0.0.r4
CATEGORIES=	www devel pear
DISTNAME=	${PORTNAME}-1.0.0RC4

MAINTAINER=	ports@FreeBSD.org
COMMENT=	WebDAV Server Baseclass

USES=	pear

.include <bsd.port.mk>
