# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-sprockets-helpers/Makefile 390829 2015-06-28 17:55:50Z sunpoet $

PORTNAME=	sprockets-helpers
PORTVERSION=	1.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Asset path helpers for Sprockets 2.x applications

LICENSE=	MIT

RUN_DEPENDS=	rubygem-sprockets3>=2.2:${PORTSDIR}/devel/rubygem-sprockets3

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
