# Created by: gugabsd <gugabsd@mundounix.com.br>
# $FreeBSD: head/textproc/py-whoosh/Makefile 365946 2014-08-24 15:20:59Z wg $

PORTNAME=	whoosh
PORTVERSION=	2.5.7
CATEGORIES=	textproc www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Whoosh-${PORTVERSION}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Featureful full-text indexing and searching in Python

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
