# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: head/devel/pear-XML_RSS/Makefile 395055 2015-08-22 22:21:44Z mat $

PORTNAME=	XML_RSS
PORTVERSION=	1.0.2
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR RSS parser

RUN_DEPENDS=	${PEARDIR}/XML/XML/Parser.php:${PORTSDIR}/devel/pear-XML_Parser

USES=	pear

.include <bsd.port.mk>
