# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: head/print/py-preppy/Makefile 371452 2014-10-24 16:42:59Z mva $

PORTNAME=	preppy
PORTVERSION=	2.3.2
CATEGORIES=	print python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	ReportLab's templating system

LICENSE=	BSD3CLAUSE

USES=		python:2.7-3.3
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
