# $FreeBSD: head/devel/gwenhywfar-gtk2/Makefile 362645 2014-07-23 09:54:02Z tijl $

PORTREVISION=	2
PKGNAMESUFFIX=	-${SLAVEPORT}

MAINTAINER=	jhale@FreeBSD.org
COMMENT=	Gwenhywfar GTK2+ support library

MASTERDIR=	${.CURDIR}/../../devel/gwenhywfar
SLAVEPORT=	gtk2
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
