# Created by: Stefan Esser <se@FreeBSD.org>
# $FreeBSD: head/archivers/unshield/Makefile 377505 2015-01-20 11:46:13Z sunpoet $

PORTNAME=	unshield
PORTVERSION=	0.6
PORTREVISION=	7
CATEGORIES=	archivers
MASTER_SITES=	SF/synce/Unshield/${PORTVERSION}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Extract data from InstallShield CAB files

LICENSE=	MIT

GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip
USE_LDCONFIG=	yes
USES=		libtool pathfix

.include <bsd.port.mk>
