# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/science/rubygem-cdo/Makefile 388612 2015-06-05 18:57:21Z sunpoet $

PORTNAME=	cdo
PORTVERSION=	1.2.5
CATEGORIES=	science rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Ruby binding to CDO (Climate Data Operators)

LICENSE=	GPLv2

RUN_DEPENDS=	${LOCALBASE}/bin/cdo:${PORTSDIR}/science/cdo

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
