# Created by: Clement Laforet <sheepkiller@cultdeadsheep.org>
# $FreeBSD: head/net/pear-Net_NNTP/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_NNTP
PORTVERSION=	1.5.0
PORTEPOCH=	1
CATEGORIES=	net news pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR implementation of the NNTP protocol

BUILD_DEPENDS=	${PEARDIR}/Net/Socket.php:${PORTSDIR}/net/pear-Net_Socket
RUN_DEPENDS=	${PEARDIR}/Net/Socket.php:${PORTSDIR}/net/pear-Net_Socket

USES=	pear

.include <bsd.port.mk>
