# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/www/R-cran-Rpad/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	Rpad
PORTVERSION=	1.3.0
PORTREVISION=	13
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Workbook-style, web-based interface to R

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
