# Created by: stas
# $FreeBSD: head/devel/boehm-gc-redirect/Makefile 369894 2014-10-03 12:52:34Z tijl $

PORTREVISION=	1

COMMENT=	Garbage collection and memory leak detection for C and C++ with malloc redirection

LICENSE=	MIT

MASTERDIR=	${.CURDIR}/../boehm-gc                                                                                                                                                        
DESCR=		${.CURDIR}/pkg-descr

GC_VARIANT=	redirect

.include "${MASTERDIR}/Makefile"
