# Created by: Edward Tomasz Napierala <trasz@FreeBSD.org>
# $FreeBSD: head/sysutils/confctl/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	confctl
PORTVERSION=	1.2
CATEGORIES=	sysutils
MASTER_SITES=	http://cloud.github.com/downloads/trasz/confctl/ \
		LOCAL/trasz

MAINTAINER=	trasz@FreeBSD.org
COMMENT=	Utility to parse and modify C-like configuration files

LICENSE=	BSD2CLAUSE

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/confctl \
		man/man1/confctl.1.gz

.include <bsd.port.mk>
