# $FreeBSD: head/devel/erlang-ssl_verify_hostname/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	ssl_verify_hostname
PORTVERSION=	1.0.5
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang library for certificate hostname validation

LICENSE=	MIT

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	deadtrickster
GH_PROJECT=	ssl_verify_hostname.erl

.include <bsd.port.mk>
