# $FreeBSD: head/french/calligra-l10n/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
PORTREVISION=	3
CATEGORIES=	french editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	French messages and documentation for Calligra

CALLIGRA_L10N=	fr

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
