# Created by: Stanislav Svirid <count@211.ru>
# $FreeBSD: head/databases/py-south/Makefile 371173 2014-10-19 08:50:17Z mva $

PORTNAME=	south
PORTVERSION=	1.0
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	South-${PORTVERSION}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Intelligent schema migrations for Django apps

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
