# $FreeBSD: head/x11-drivers/xf86-video-siliconmotion/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-video-siliconmotion
PORTVERSION=	1.7.7
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org siliconmotion display driver

XORG_CAT=	driver

.include <bsd.port.mk>
