# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py-curtsies/Makefile 381097 2015-03-12 14:58:00Z sunpoet $

PORTNAME=	curtsies
PORTVERSION=	0.1.19
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Curses-like terminal wrapper, with colored strings

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}blessings>=1.5:${PORTSDIR}/devel/py-blessings

USE_PYTHON=	autoplist distutils
USES=		python

.include <bsd.port.mk>
