# Created by: Anish Mistry (<amistry@am-productions.biz>)
# $FreeBSD: head/devel/pear-Validate_Finance/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Validate_Finance
PORTVERSION=	0.5.6
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR Finance Validation class

BUILD_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate
RUN_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate

USES=	pear

.include <bsd.port.mk>
