# Created by: ijliao
# $FreeBSD: head/devel/py-fortran/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	fortran
PORTVERSION=	8.5.3
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	SF/py${PORTNAME}/py${PORTNAME}/8.5
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Pyfort-${PORTVERSION}

MAINTAINER=	wenheping@gmail.com
COMMENT=	Creating extensions to the Python language with Fortran routines

RUN_DEPENDS=	${PYNUMERIC}

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
