# Created by: Andriy Pylypenko <bamby@sippysoft.com>
# $FreeBSD: head/www/py-wsgiauth/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	wsgiauth
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bamby@sippysoft.com
COMMENT=	WSGI authentication middleware

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
