# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-jquery-ui-themes/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	jquery-ui-themes
PORTVERSION=	0.0.11
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Allows inclusion of pre-built jquery themes without editing

LICENSE=	MIT

RUN_DEPENDS=	rubygem-httparty>=0:${PORTSDIR}/www/rubygem-httparty

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
