# $FreeBSD: head/editors/libreoffice-ca_valencia/Makefile 357643 2014-06-12 23:43:05Z jkim $

LO_I18N=	ca_valencia
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
