# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/textproc/php5-pspell/Makefile 389655 2015-06-14 20:23:09Z ale $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pspell

.include "${MASTERDIR}/Makefile"
