# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/net/py-gspread/Makefile 368335 2014-09-16 16:20:26Z skreuzer $

PORTNAME=	gspread
PORTVERSION=	0.2.2
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Google Spreadsheets Python API

LICENSE=	MIT

USES=	python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
