# Created by: jonny@jonny.eng.br
# $FreeBSD: head/mail/pop3gwd/Makefile 356626 2014-06-05 11:10:08Z pawel $

PORTNAME=	pop3gwd
PORTVERSION=	1.2
CATEGORIES=	mail net
MASTER_SITES=	http://fresh.t-systems-sfr.com/linux/src/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	App-level proxy for Mail retrieval behind Firewalls

WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
