# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: head/net/pear-Net_Nmap/Makefile 395055 2015-08-22 22:21:44Z mat $

PORTNAME=	Net_Nmap
PORTVERSION=	1.0.5
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple Wrapper Class for the Nmap Utility

LICENSE=	LGPL3

BUILD_DEPENDS=	${PEARDIR}/XML/XML/Parser.php:${PORTSDIR}/devel/pear-XML_Parser
RUN_DEPENDS:=	${PEARDIR}/XML/XML/Parser.php:${PORTSDIR}/devel/pear-XML_Parser

USES=	pear

.include <bsd.port.mk>
