# $FreeBSD: head/portuguese/libreoffice-pt_BR/Makefile 371023 2014-10-16 21:14:18Z jkim $

LO_I18N=	pt_BR
LO_HAS_HELPPACK=	yes
CATEGORIES=	portuguese editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
