# Created by: Pete Fritchman <petef@databits.net>
# $FreeBSD: head/x11-fonts/p5-Font-AFM/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Font-AFM
PORTVERSION=	1.20
PORTREVISION=	1
CATEGORIES=	x11-fonts perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Interface to Adobe font metrics files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
