# Created by: Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: head/editors/lazarus-lcl-nogui/Makefile 393766 2015-08-09 08:06:43Z acm $

PORTREVISION=	1
PKGNAMESUFFIX=	-lcl-nogui

COMMENT=	Lazarus components library - No gui backend

BUILD_DEPENDS=	${LCL_UNITS_DIR}/alllclunits.ppu:${PORTSDIR}/editors/lazarus-lcl-units

LCL_INTERFACE=	nogui

MASTERDIR=	${.CURDIR}/../../editors/lazarus

OPT=		#
.include "${MASTERDIR}/Makefile"
