# $FreeBSD: head/emulators/qmc2/files/Makefile 340722 2014-01-22 17:00:46Z mat $

all:	qmc2/qmc2-sdlmame qmc2-sdlmess/qmc2-sdlmess

qmc2/qmc2-sdlmame:
	${MAKE} -C qmc2 EMULATOR=SDLMAME

qmc2-sdlmess/qmc2-sdlmess:
	${MAKE} -C qmc2-sdlmess EMULATOR=SDLMESS
