# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/dns/pear-Net_DNS2/Makefile 384573 2015-04-23 13:29:00Z vanilla $

PORTNAME=	Net_DNS2
PORTVERSION=	1.4.1
CATEGORIES=	dns net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP5 Resolver library used to communicate with a DNS server

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		pear

.include <bsd.port.mk>
