# Created by: Bryan Drewery <bryan@shatow.net>
# $FreeBSD: head/devel/rubygem-backports/Makefile 394128 2015-08-13 17:35:33Z sunpoet $

PORTNAME=	backports
PORTVERSION=	3.6.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby 1.9 backports for 1.8

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
