# $FreeBSD: head/www/rubygem-turbolinks/Makefile 393813 2015-08-09 18:30:17Z swills $

PORTNAME=	turbolinks
PORTVERSION=	2.5.3
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Turbolinks makes following links in your web application faster

LICENSE=	MIT

RUN_DEPENDS?=	rubygem-coffee-rails4>=4.0.1:${PORTSDIR}/devel/rubygem-coffee-rails4

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
