# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/devel/py-lockfile/Makefile 369276 2014-09-25 17:10:43Z wg $

PORTNAME=	lockfile
PORTVERSION=	0.10.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Platform-independent file locking module

LICENSE=	MIT

BUILD_DEPENDS=	${PYTHON_PKGNAMEPREFIX}pbr>0:${PORTSDIR}/devel/py-pbr

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
