# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: head/sysutils/rubygem-bundler/Makefile 392801 2015-07-24 09:00:17Z sunpoet $

PORTNAME=	bundler
PORTVERSION=	1.10.6
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Tool that manages gem dependencies for ruby applications

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/bundle bin/bundler

.include <bsd.port.mk>
