# Created by: Evan Sarmiento <bsdports@wayfair.com>
# $FreeBSD: head/devel/rubygem-bson/Makefile 393345 2015-07-31 16:26:28Z sunpoet $

PORTNAME=	bson
PORTVERSION=	3.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Full featured BSON specification implementation in Ruby

LICENSE=	APACHE20

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
