# Created by: ehaupt@FreeBSD.org
# $FreeBSD: head/net-mgmt/py-ipcalc/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	ipcalc
PORTVERSION=	1.1.2
CATEGORIES=	net-mgmt python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Module to perform IP subnet calculations

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
