# $FreeBSD: head/security/pear-Auth_HTTP/Makefile 369311 2014-09-26 09:05:59Z bapt $

PORTNAME=	Auth_HTTP
PORTVERSION=	2.1.8
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR HTTP authentication

USES=	pear

.include <bsd.port.mk>
