# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/mail/pear-Contact_Vcard_Parse/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Contact_Vcard_Parse
PORTVERSION=	1.32.0
CATEGORIES=	mail www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class to parse vCard 2.1 and 3.0 files

USES=	pear

.include <bsd.port.mk>
