# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/devel/pear-Validate_AU/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Validate_AU
PORTVERSION=	0.1.4
PORTREVISION=	1
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR data validation class for Australia

USES=	pear

.include <bsd.port.mk>
