# $FreeBSD: head/editors/calligra-l10n-sk/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
PORTREVISION=	3
CATEGORIES=	editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Slovak messages and documentation for Calligra

CALLIGRA_L10N=	sk

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
