# Created by: Roman Neuhauser (<neuhauser@bellavista.cz>)
# $FreeBSD: head/net/pear-Net_URL/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_URL
PORTVERSION=	1.0.15
CATEGORIES=	net www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Easy parsing of URLs

USES=	pear

.include <bsd.port.mk>
