# Created by: Michael Schout <mschout@gkg.net>
# $FreeBSD: head/devel/pear-HTML_Select/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_Select
PORTVERSION=	1.3.1
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR::HTML_Select is a class for generating HTML form select elements

BUILD_DEPENDS=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common
RUN_DEPENDS=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common

USES=	pear

.include <bsd.port.mk>
