# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/security/pear-Crypt_MicroID/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Crypt_MicroID
PORTVERSION=	0.1.0
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP MicroID library

USES=	pear

.include <bsd.port.mk>
