# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/databases/pear-Structures_DataGrid_DataSource_Array/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Structures_DataGrid_DataSource_Array
PORTVERSION=	0.1.4
CATEGORIES=	databases www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	DataSource driver using arrays

BUILD_DEPENDS=	${PEARDIR}/Structures/DataGrid.php:${PORTSDIR}/devel/pear-Structures_DataGrid
RUN_DEPENDS=	${PEARDIR}/Structures/DataGrid.php:${PORTSDIR}/devel/pear-Structures_DataGrid

USES=		pear

.include <bsd.port.mk>
