# $FreeBSD: head/x11-drivers/xf86-input-acecad/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-input-acecad
PORTVERSION=	1.5.0
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org acecad input driver

XORG_CAT=	driver

.include <bsd.port.mk>
