# Created by: Oleg Sharoiko <os@rsu.ru>
# $FreeBSD: head/databases/pear-MDB/Makefile 395055 2015-08-22 22:21:44Z mat $

PORTNAME=	MDB
PORTVERSION=	1.3.0
CATEGORIES=	databases www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR unified API for DB access, based on user meta data

BUILD_DEPENDS=	${PEARDIR}/XML/XML/Parser.php:${PORTSDIR}/devel/pear-XML_Parser
RUN_DEPENDS=	${PEARDIR}/XML/XML/Parser.php:${PORTSDIR}/devel/pear-XML_Parser

USES=		pear

.include <bsd.port.mk>
