# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/rubygem-fastimage/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	fastimage
PORTVERSION=	1.7.0
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	FastImage finds the size or type of an image

LICENSE=	MIT

RUN_DEPENDS=	rubygem-addressable>=2.3.5:${PORTSDIR}/www/rubygem-addressable

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
