# $FreeBSD: head/devel/elixir-msgpax/Makefile 392529 2015-07-19 19:34:12Z olgeni $

PORTNAME=	msgpax
PORTVERSION=	0.8.0
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	MessagePack implementation for Elixir

LICENSE=	ISCL

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	lexmag

.include <bsd.port.mk>
