# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/www/pear-Services_Digg/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_Digg
PORTVERSION=	0.4.7
PORTREVISION=	1
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP interface to Digg's API

USES=	pear
USE_PHP=	curl

.include <bsd.port.mk>
