# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php56-mcrypt/Makefile 384787 2015-04-26 12:33:09Z ale $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-mcrypt

.include "${MASTERDIR}/Makefile"
