# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: head/devel/rubygem-hitimes/Makefile 365872 2014-08-24 02:22:38Z swills $

PORTNAME=	hitimes
PORTVERSION=	1.2.2
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	High resolution timer library for Ruby

LICENSE=	ISCL

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
