# Created by: chinsan
# $FreeBSD: head/devel/pecl-htscanner/Makefile 379804 2015-02-24 15:23:01Z vanilla $

PORTNAME=	htscanner
PORTVERSION=	1.0.1
CATEGORIES=	devel pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Support htaccess for PHP

LICENSE=	PHP30

USES=		tar:tgz
USE_PHP=	yes
USE_PHPEXT=	yes

CONFIGURE_ARGS=	--enable-htscanner

.include <bsd.port.mk>
