# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/devel/py-jsonschema/Makefile 369272 2014-09-25 16:43:07Z wg $

PORTNAME=	jsonschema
PORTVERSION=	2.4.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	JSON Schema validation for Python

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
