# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/net/pear-File_Bittorrent2/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	File_Bittorrent2
DISTVERSION=	1.3.1
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Decode and Encode data in Bittorrent format

USES=	pear

.include <bsd.port.mk>
