# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/net/pear-Net_Ident/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_Ident
PORTVERSION=	1.1.0
CATEGORIES=	net www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR identification protocol implementation

USES=	pear

.include <bsd.port.mk>
