# Created by: Frederic Culot <culot@FreeBSD.org>
# $FreeBSD: head/devel/p5-Devel-GlobalDestruction-XS/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Devel-GlobalDestruction-XS
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Faster implementation of the Devel::GlobalDestruction API

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
