# Created by: Oliver Lehmann <oliver@FreeBSD.org>
# $FreeBSD: head/security/courier-authlib-base/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTREVISION=	1
PKGNAMESUFFIX=	-base

COMMENT=	Courier authentication library base
CATEGORIES=	security mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

USE_LDCONFIG=	${PREFIX}/lib/${PORTNAME}

.include "${MASTERDIR}/Makefile"
