# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD: head/www/py-websocket-client/Makefile 381119 2015-03-12 17:12:19Z sunpoet $

PORTNAME=	websocket-client
PORTVERSION=	0.16.0
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Websocket client for python

LICENSE=	ISCL

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
