# $FreeBSD: head/devel/p5-Devel-FindPerl/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Devel-FindPerl
PORTVERSION=	0.012
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Find the path to your perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
