# Created by: jhay
# $FreeBSD: head/net/p5-Net-SMPP/Makefile 388072 2015-05-31 13:17:29Z amdmi3 $

PORTNAME=	Net-SMPP
PORTVERSION=	1.19
PORTREVISION=	2
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jhay@FreeBSD.org
COMMENT=	Net::SMPP - pure Perl implementation of SMPP 3.4 over TCP

USES=		perl5 shebangfix
SHEBANG_FILES=	*.pl
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
