# Created by: peter.schuller@infidyne.com
# $FreeBSD: head/textproc/rubygem-liquid/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	liquid
PORTVERSION=	2.6.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for rendering safe templates

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
