# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: head/security/pear-Crypt_DiffieHellman/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Crypt_DiffieHellman
PORTVERSION=	0.2.6
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class implementing Diffie-Hellman Key Exchange protocol for PHP5

USES=	pear
USE_PHP=	bcmath mbstring gmp

.include <bsd.port.mk>
