# Created by: Thomas Zander <riggs@FreeBSD.org>
# $FreeBSD: head/devel/py-validictory/Makefile 377395 2015-01-19 10:18:22Z rm $

PORTNAME=	validictory
PORTVERSION=	1.0.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	General purpose Python data validator

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
