# Created by: Evan Sarmiento <bsdports@wayfair.com>
# $FreeBSD: head/devel/rubygem-bson1/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	bson
PORTVERSION=	1.12.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	1

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Full featured BSON specification implementation in Ruby

LICENSE=	APACHE20

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	limit:^1\.

.include <bsd.port.mk>
