# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: head/graphics/atril-lite/Makefile 393431 2015-08-02 16:06:16Z kwm $

PORTREVISION=	5
PKGNAMESUFFIX=	-lite

COMMENT=	MATE multi-format document viewer

OPTIONS_EXCLUDE=	CAJA

MASTERDIR=      ${.CURDIR}/../../graphics/atril
SLAVEPORT=      lite
DESCR=		${.CURDIR}/pkg-descr
PLIST=          ${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
