# Created by: Boris Samorodov <bsam@FreeBSD.org>
# $FreeBSD: head/chinese/eric6/Makefile 380767 2015-03-08 10:40:13Z bsam $

CATEGORIES=	chinese devel python
I18N_LANG=	zh_CN.GB2312

.include "${.CURDIR}/../../devel/eric6/Makefile.inc"
