# Created by: loader <loader@freebsdmall.com>
# $FreeBSD: head/devel/py-glob2/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	glob2
PORTVERSION=	0.4.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	loader@freebsdmall.com
COMMENT=	Glob that captures patterns and supports recursive wildcards

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
