# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: head/net/courier-authlib-ldap/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTREVISION=	1
PKGNAMESUFFIX=	-ldap

COMMENT=	LDAP support for the Courier authentication library
CATEGORIES=	net mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

.include "${MASTERDIR}/Makefile"
