# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/devel/p5-Exporter-Easy/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Exporter-Easy
PORTVERSION=	0.17
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Takes the drudgery out of Exporting symbols

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
