# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/security/pear-Crypt_HMAC2/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Crypt_HMAC2
PORTVERSION=	1.0.0
CATEGORIES=	security www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Implementation of Hashed Message Authentication Code for PHP5

USES=	pear

.include <bsd.port.mk>
