# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/chinese/p5-Lingua-ZH-WordSegmenter/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Lingua-ZH-WordSegmenter
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	chinese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simplified Chinese Word Segmentation

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
