# $FreeBSD: head/devel/msgpuck/Makefile 391633 2015-07-09 14:43:36Z vg $

PORTNAME=	msgpuck
PORTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	vg@FreeBSD.org
COMMENT=	MsgPack binary serialization library in a self-contained header

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_PROJECT=	msgpuck
GH_ACCOUNT=	tarantool

USES=		cmake

.include <bsd.port.mk>
