# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/sysutils/pear-I18Nv2/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	I18Nv2
PORTVERSION=	0.11.4
CATEGORIES=	sysutils devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR Internationalization

USES=	pear
USE_PHP=	iconv

.include <bsd.port.mk>
