# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: head/devel/cld/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	cld
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	GOOGLE_CODE
PROJECTHOST=	chromium-compact-language-detector
DISTNAME=	compact-language-detector-${PORTVERSION}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Chromium compact language detector library

USES=		libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
