# Created by: Gerrit Beine (<gerrit.beine@gmx.de>)
# $FreeBSD: head/devel/pear-HTML_QuickForm2/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_QuickForm2
PORTVERSION=	0.6.1
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP5 rewrite of the HTML_QuickForm package

BUILD_DEPENDS=	${PEARDIR}/HTML/Common2.php:${PORTSDIR}/devel/pear-HTML_Common2
RUN_DEPENDS=	${PEARDIR}/HTML/Common2.php:${PORTSDIR}/devel/pear-HTML_Common2

USES=	pear

.include <bsd.port.mk>
