# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-PHP_Compat/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	PHP_Compat
PORTVERSION=	1.5.0
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Provides missing functionality for older versions of PHP

PORTSCOUT=	skipv:1.6.0a1,1.6.0a2
USES=	pear

.include <bsd.port.mk>
