# Created by: Olivier Duchateau <duchateau.olivier@gmail.com>
# $FreeBSD: head/www/py-flask-uploads/Makefile 366562 2014-08-29 20:57:09Z olivierd $

PORTNAME=	Flask-Uploads
PORTVERSION=	0.1.3
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	Flexible and efficient upload handling for Flask

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}Flask>=0.10:${PORTSDIR}/www/py-flask

USES=	python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
