# Created by: Loic Pefferkorn <loic-freebsd@loicp.eu>
# $FreeBSD: head/textproc/rubygem-heredoc_unindent/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	heredoc_unindent
PORTVERSION=	1.2.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	loic-freebsd@loicp.eu
COMMENT=	Removes common margin from indented strings

LICENSE=	MIT

RUN_DEPENDS=	rubygem-hoe>=2.9.6:${PORTSDIR}/devel/rubygem-hoe

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
