# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-doParallel/Makefile 393935 2015-08-11 08:51:58Z tota $

PORTNAME=	doParallel
PORTVERSION=	1.0.8
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Foreach parallel adaptor for the parallel package

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-foreach>=1.2.0:${PORTSDIR}/devel/R-cran-foreach \
		R-cran-iterators>=1.0.0:${PORTSDIR}/devel/R-cran-iterators

USES=	cran:auto-plist

.include <bsd.port.mk>
