# Created by: chinsan
# $FreeBSD: head/net/pear-Net_Whois/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_Whois
PORTVERSION=	1.0.5
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tool to query internet domain name services

USES=	pear

RUN_DEPENDS=	${PEARDIR}/Net/Socket.php:${PORTSDIR}/net/pear-Net_Socket

.include <bsd.port.mk>
