# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/textproc/pear-Horde_Pdf/Makefile 385085 2015-05-01 07:11:54Z mm $

PORTNAME=	Horde_Pdf
PORTVERSION=	2.0.5
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde PDF library

USES=	horde
USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.mk>
