# $FreeBSD: head/devel/rubygem-font-awesome-rails/Makefile 393346 2015-07-31 16:26:33Z sunpoet $

PORTNAME=	font-awesome-rails
PORTVERSION=	4.4.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides the Font-Awesome web fonts and stylesheets as a Rails engine

LICENSE=	MIT OFL11
LICENSE_COMB=	dual

RUN_DEPENDS=	rubygem-railties>=3.2:${PORTSDIR}/www/rubygem-railties

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
