# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/p5-Data-IEEE754/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Data-IEEE754
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Pack and unpack big-endian IEEE754 floats and doubles

LICENSE=	ART20

TEST_DEPENDS=	p5-Test-Bits>=0:${PORTSDIR}/devel/p5-Test-Bits

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
