# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: head/devel/p5-B-Keywords/Makefile 379593 2015-02-22 10:44:07Z sunpoet $

PORTNAME=	B-Keywords
PORTVERSION=	1.14
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lists of reserved barewords and symbol names

LICENSE=	ART10 GPLv2
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
