# Created by: Mathieu Arnold <mat@FreeBSD.org>
# $FreeBSD: head/devel/p5-ExtUtils-CBuilder/Makefile 388487 2015-06-03 20:05:24Z sunpoet $

PORTNAME=	ExtUtils-CBuilder
PORTVERSION=	0.280223
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Compile and link C code for Perl modules

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
