# $FreeBSD: head/x11-drivers/xf86-input-hyperpen/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-input-hyperpen
PORTVERSION=	1.4.1
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org hyperpen input driver

XORG_CAT=	driver

.include <bsd.port.mk>
