# Created by: Nick Hilliard <nick@foobar.org>
# $FreeBSD: head/www/pear-Structures_DataGrid_Renderer_Flexy/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Structures_DataGrid_Renderer_Flexy
PORTVERSION=	0.1.4
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Renderer for pear-Structures_DataGrid using HTML_Template_Flexy

RUN_DEPENDS=	${PEARDIR}/Structures/DataGrid.php:${PORTSDIR}/devel/pear-Structures_DataGrid \
		${PEARDIR}/HTML/Template/Flexy.php:${PORTSDIR}/devel/pear-HTML_Template_Flexy \
		${PEARDIR}/Structures/DataGrid/Renderer/Pager.php:${PORTSDIR}/www/pear-Structures_DataGrid_Renderer_Pager

USES=	pear

.include <bsd.port.mk>
