# Created by: Ed Schouten <ed@FreeBSD.org>
# $FreeBSD: head/devel/cloudabi-binutils/Makefile 392531 2015-07-19 19:48:34Z bapt $

PKGNAMEPREFIX=	cloudabi-
PORTREVISION=	1

MAINTAINER=	ed@FreeBSD.org
COMMENT=	GNU Binutils for CloudABI cross-development

MASTERDIR=	${.CURDIR}/../binutils
PATCHDIR=	${.CURDIR}/files
PLIST=		${.CURDIR}/pkg-plist

BUTARGET=	x86_64-unknown-cloudabi

.include "${MASTERDIR}/Makefile"
