# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py-simplegeneric/Makefile 364929 2014-08-15 03:43:54Z sunpoet $

PORTNAME=	simplegeneric
PORTVERSION=	0.8.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simple generic functions

LICENSE=	ZPL21

USE_PYTHON=	autoplist distutils
USES=		python zip

.include <bsd.port.mk>
