# Created by: Alexander Botero-Lowry <alex@foxybanana.com>
# $FreeBSD: head/news/py-yenc/Makefile 371452 2014-10-24 16:42:59Z mva $

PORTNAME=	yenc
PORTVERSION=	0.3
CATEGORIES=	news python
MASTER_SITES=	http://sabnzbd.sourceforge.net/
		
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jlaffaye@FreeBSD.org
COMMENT=	yenc decoding module for Python in C

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
