# $FreeBSD: head/devel/rubygem-gemcutter/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	gemcutter
PORTVERSION=	0.7.1
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Extensions to RubyGems for managing gems and more on RubyGems.org

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
