# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/biology/python-nexus/Makefile 371171 2014-10-19 07:38:11Z mva $

PORTNAME=	python-nexus
PORTVERSION=	0.87
PORTREVISION=	1
CATEGORIES=	biology python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Generic nexus file format reader for python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
