# $FreeBSD: head/devel/erlang-protobuffs/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	protobuffs
PORTVERSION=	0.8.1p5
PORTREVISION=	1
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Protocol Buffers interface for Erlang

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	basho
GH_PROJECT=	erlang_protobuffs

.include <bsd.port.mk>
