# $FreeBSD: head/sysutils/ezjail/Makefile 386692 2015-05-18 17:10:45Z bdrewery $

PORTNAME=	ezjail
PORTVERSION=	3.4.1
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://erdgeist.org/arts/software/ezjail/

MAINTAINER=	erdgeist@erdgeist.org
COMMENT=	Framework to easily create, manipulate, and run FreeBSD jails

USES=		tar:bzip2

MAKE_ENV=	DESTDIR=${STAGEDIR}

.include <bsd.port.mk>
