# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/devel/py-unipath/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	Unipath
PORTVERSION=	1.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Object-oriented alternative to os/os.path/shutil

LICENSE=	PSFL

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
