# Created by: Hye-Shik Chang
# $FreeBSD: head/devel/py-parsing/Makefile 388874 2015-06-08 19:38:45Z sunpoet $

PORTNAME=	parsing
PORTVERSION=	2.0.3
CATEGORIES=	devel python
MASTER_SITES=	SF/py${PORTNAME}/py${PORTNAME}/py${PORTNAME}-${PORTVERSION}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	pyparsing-${PORTVERSION}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	General parsing module for Python

LICENSE=	MIT

USE_PYTHON=	autoplist distutils
USES=		python

.include <bsd.port.mk>
