# Created by: Li-Wen Hsu <lwhsu@FreeBSD.org>
# $FreeBSD: head/databases/py-pymysql/Makefile 371173 2014-10-19 08:50:17Z mva $

PORTNAME=	pymysql
PORTVERSION=	0.6.2
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
DISTNAME=	PyMySQL-${PORTVERSION}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Pure Python MySQL Driver

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
