# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/devel/p5-ExtUtils-LibBuilder/Makefile 376484 2015-01-07 17:56:25Z sunpoet $

PORTNAME=	ExtUtils-LibBuilder
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to build C libraries

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
