# Created by: George Neville-Neil gnn@freebsd.org
# $FreeBSD: head/sysutils/mbgtools/Makefile 367604 2014-09-07 20:21:34Z antoine $

PORTNAME=	mbgtools
DISTVERSION=	fbsd-dev-2013-06-26
CATEGORIES=	sysutils
MASTER_SITES=	http://www.meinberg.de/download/drivers/

MAINTAINER=	gnn@FreeBSD.org
COMMENT=	Drivers and tools for Meinberg PTP/GPS cards

LICENSE=	BSD

USE_RC_SUBR=	mbgsvcd

USES=		kmod uidfix

.include <bsd.port.mk>
