# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: head/databases/rubygem-globalid/Makefile 394127 2015-08-13 17:35:28Z sunpoet $

PORTNAME=	globalid
PORTVERSION=	0.3.6
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	URIs for your models makes it easy to pass references around

LICENSE=	MIT

RUN_DEPENDS=	rubygem-activesupport4>=4.1.0:${PORTSDIR}/devel/rubygem-activesupport4

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
