# $FreeBSD: head/x11-themes/gnome-icons-gion/Makefile 354929 2014-05-23 11:13:17Z olgeni $

PORTNAME=	gion
PORTVERSION=	0.1.2
CATEGORIES=	x11-themes gnome
MASTER_SITES=	http://www.silvestre.com.ar/icons/
DISTNAME=	Gion-${PORTVERSION}

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Gion Icons for Gnome

USES=		tar:bzip2
WRKSRC=		"${WRKDIR}/Gion"

.include "${.CURDIR}/../gnome-icons/bsd.gnome-icons.mk"
.include <bsd.port.mk>
