# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/www/py-uliweb/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	uliweb
PORTVERSION=	0.3.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Uliweb-${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Easy python web framework

LICENSE=	BSD2CLAUSE

USES=		dos2unix python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
