# Created by: Foxfair Hu <foxfair@FreeBSD.org>
# $FreeBSD: head/math/p5-Math-Round/Makefile 376132 2015-01-03 17:13:22Z sunpoet $

PORTNAME=	Math-Round
PORTVERSION=	0.07
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Perl extension for rounding numbers

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
