# $FreeBSD: head/arabic/libreoffice/Makefile 371023 2014-10-16 21:14:18Z jkim $

LO_I18N=	ar
CATEGORIES=	arabic editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"
.include <bsd.port.mk>
