# $FreeBSD: head/devel/py-Products.PloneLanguageTool/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	Products.PloneLanguageTool
PORTVERSION=	3.2.7
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Allows to set the available languages in Plone site

LICENSE=	GPLv2

USES=		python zip
USE_PYTHON=	distutils

.include <bsd.port.mk>
