# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/textproc/py-markdown2/Makefile 374183 2014-12-07 10:01:36Z mva $

PORTNAME=	markdown2
PORTVERSION=	2.2.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Fast and complete Python implementation of Markdown

LICENSE=	MIT

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
