# Created by: Mark Huizer <xaa+ports@timewasters.nl>
# $FreeBSD: head/games/pear-Games_Chess/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Games_Chess
PORTVERSION=	1.0.1
CATEGORIES=	games devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR methods for constructing and validating chess games in PGN

USES=	pear

.include <bsd.port.mk>
