# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/converters/p5-Encode-Detect-CJK/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Encode-Detect-CJK
PORTVERSION=	2.0.2
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Charset detector for East Asia charsets and website contents

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
