# $FreeBSD: head/x11-drivers/xf86-video-tseng/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-video-tseng
PORTVERSION=	1.2.5
PORTREVISION=	6
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org tseng display driver

XORG_CAT=	driver

.include <bsd.port.mk>
