# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: head/devel/rubygem-state_machine/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	state_machine
PORTVERSION=	1.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Support for creating state machines for attributes on any Ruby class

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
