# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/p5-DBD-mysql51/Makefile 390881 2015-06-29 04:58:43Z sunpoet $

PKGNAMESUFFIX=	51

COMMENT=	MySQL 5.1 driver for the Perl5 Database Interface (DBI)

CONFLICTS_INSTALL=	p5-DBD-mysql-[0-9]* p5-DBD-mysql5[02-9]-[0-9]*

WANT_MYSQL_VER=	51

MASTERDIR=	${.CURDIR}/../p5-DBD-mysql

.include "${MASTERDIR}/Makefile"
