# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: head/www/py-django-tinymce/Makefile 389552 2015-06-13 20:17:08Z sunpoet $

PORTNAME=	django-tinymce
PORTVERSION=	1.5.3
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	Django application to use TinyMCE editor

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django>=0:${PORTSDIR}/www/py-django

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
