# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-evaluate/Makefile 394255 2015-08-14 20:20:02Z tota $

PORTNAME=	evaluate
PORTVERSION=	0.7.2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Parsing and Evaluation Tools

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-stringr>=0.6.2:${PORTSDIR}/textproc/R-cran-stringr

USES=	cran:auto-plist

.include <bsd.port.mk>
