# Created by: Zach Thompson <hideo@lastamericanempire.com>
# $FreeBSD: head/finance/p5-Locale-Currency-Format/Makefile 392836 2015-07-24 18:14:29Z sunpoet $

PORTNAME=	Locale-Currency-Format
PORTVERSION=	1.33
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl functions for formatting monetary values

LICENSE=	ART20 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
