# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: head/devel/rubygem-tins0/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	tins
PORTVERSION=	0.13.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	0

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Useful tools library in Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	limit:^0\.

.include <bsd.port.mk>
