# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: head/devel/py-country/Makefile 395180 2015-08-24 16:53:02Z demon $

PORTNAME=	country
PORTVERSION=	1.14
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	pycountry-${PORTVERSION}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Python API for ISO country, subdivision, language and currency

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
