# Created by: Alexander Logvinov <ports@logvinov,com>
# $FreeBSD: head/databases/rubygem-jdbc-mysql/Makefile 392413 2015-07-18 11:13:35Z sunpoet $

PORTNAME=	jdbc-mysql
PORTVERSION=	5.1.36
CATEGORIES=	databases rubygems java
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	MySQL JDBC driver for JRuby

LICENSE=	GPLv2

RUN_DEPENDS=	jruby:${PORTSDIR}/lang/jruby

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
