# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD: head/devel/rubygem-jbuilder-rails41/Makefile 393801 2015-08-09 16:13:27Z swills $

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-activesupport41>=4.1.12:${PORTSDIR}/devel/rubygem-activesupport41 \
	rubygem-multi_json>=1.2:${PORTSDIR}/devel/rubygem-multi_json

MASTERDIR=	${.CURDIR}/../rubygem-jbuilder

.include "${MASTERDIR}/Makefile"
