# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/databases/pear-DBA_Relational/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	DBA_Relational
PORTVERSION=	0.2.0
CATEGORIES=	databases www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Berkely-style database abstraction class

PORTSCOUT=	skipv:0.19

USES=	pear

.include <bsd.port.mk>
