# Created by: wenheping <wenheping@gmail.com>
# $FreeBSD: head/net/pear-URI_Template/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	URI_Template
PORTVERSION=	0.3.3
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Parser for URI Templates

USES=	pear

.include <bsd.port.mk>
