# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-stringi/Makefile 391133 2015-07-02 11:19:25Z tota $

PORTNAME=	stringi
DISTVERSION=	0.5-5
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Character String Processing Facilities

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libicui18n.so:${PORTSDIR}/devel/icu

USES=	cran:auto-plist pkgconfig:build

.include <bsd.port.mk>
