# $FreeBSD: head/news/husky-areafix/Makefile 365427 2014-08-19 22:10:13Z marino $

PORTNAME=	husky-areafix
CATEGORIES=	news mail

MAINTAINER=	osharoiko@gmail.com
COMMENT=	Husky FTN areafix library

LIB_DEPENDS=	libfidoconfig.so:${PORTSDIR}/news/husky-fidoconf

USE_LDCONFIG=	yes

MASTERDIR=	${.CURDIR}/../husky
COMPONENT_SUBDIR=	areafix

.include <bsd.port.mk>
