# $FreeBSD: head/devel/py-Products.contentmigration/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	Products.contentmigration
PORTVERSION=	2.1.5
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Generic content migration framework for Plone

LICENSE=	LGPL20

USES=		python:2 zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
