# Created by: Matthew Holder <sixxgate@hotmail.com>
# $FreeBSD: head/deskutils/mrundlg/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	mrundlg
PORTVERSION=	1.0
PORTREVISION=	3
CATEGORIES=	deskutils
# MASTER_SITES=	http://matt.sixxgate.com/files/
MASTER_SITES=	FREEBSD

MAINTAINER=	sixxgate@hotmail.com
COMMENT=	Application / program launcher for Motif

BROKEN=		Unfetchable
USES=		imake motif tar:bzip2
USE_XORG=	x11 xmu xt

.include <bsd.port.mk>
