# $FreeBSD: head/devel/erlang-jsx/Makefile 394899 2015-08-20 17:16:40Z olgeni $

PORTNAME=	jsx
PORTVERSION=	2.7.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang application for consuming, producing and manipulating JSON

LICENSE=	MIT

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	talentdeficit

.include <bsd.port.mk>
