# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: head/audio/gstreamer-plugins-amrnb/Makefile 352119 2014-04-25 12:46:45Z bapt $

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer OpenCore based Adaptive Multi-Rate Narrow-Band plugin

GST_PLUGIN=	amrnb

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
