# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/science/R-cran-Epi/Makefile 389321 2015-06-13 06:04:57Z tota $

PORTNAME=	Epi
PORTVERSION=	1.1.67
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Package for statistical analysis in epidemiology

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
