# Created by: William Grzybowski <william88@gmail.com>
# $FreeBSD: head/devel/py-pytest-runner/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	pytest-runner
PORTVERSION=	2.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Test support for pytest runner in setup.py

BUILD_DEPENDS=	${PYTHON_PKGNAMEPREFIX}hgtools>=0:${PORTSDIR}/devel/py-hgtools

USES=		python:2 zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
