# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/net-mgmt/p5-Xymon-Client/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Xymon-Client
PORTVERSION=	0.08
PORTREVISION=	1
CATEGORIES=	net-mgmt
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Interface to xymon/hobbit client

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
