# Created by: Cezary Morga <cm@therek.net>
# $FreeBSD: head/devel/p5-Thread-Queue/Makefile 395367 2015-08-26 15:21:43Z culot $

PORTNAME=	Thread-Queue
PORTVERSION=	3.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Perl5 thread-safe queues

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
