# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: head/www/py-tmdb3/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	tmdb3
PORTVERSION=	0.6.17
CATEGORIES=	www devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	TheMovieDB.org APIv3 interface

USES=		python:2 zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
