# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/sysutils/pear-File/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	File
PORTVERSION=	1.4.1
PORTEPOCH=	2
CATEGORIES=	sysutils www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR common file and directory routines

USES=		pear
USE_PHP=	pcre

.include <bsd.port.mk>
