# Created by: Nick Hilliard <nick@foobar.org>
# $FreeBSD: head/devel/pear-Structures_DataGrid_Renderer_HTMLSortForm/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Structures_DataGrid_Renderer_HTMLSortForm
PORTVERSION=	0.1.3
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	HTMLSortForm Renderer for pear-Structures_DataGrid

RUN_DEPENDS=	${PEARDIR}/Structures/DataGrid.php:${PORTSDIR}/devel/pear-Structures_DataGrid \
		${PEARDIR}/HTML/QuickForm.php:${PORTSDIR}/devel/pear-HTML_QuickForm

USES=	pear

.include <bsd.port.mk>
