# Created by: Olivier Duchateau <duchateau.olivier@gmail.com>
# $FreeBSD: head/security/py-certifi/Makefile 385136 2015-05-01 18:15:00Z rm $

PORTNAME=	certifi
PORTVERSION=	2015.04.28
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Mozilla's SSL certificates

LICENSE=	ISCL

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
