# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: head/www/rubygem-faraday/Makefile 391473 2015-07-06 18:05:37Z sunpoet $

PORTNAME=	faraday
PORTVERSION=	0.9.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	HTTP/REST API client library in Ruby

LICENSE=	MIT

RUN_DEPENDS=	rubygem-multipart-post>=1.2:${PORTSDIR}/www/rubygem-multipart-post

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
