# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/graphics/php5-gd/Makefile 394290 2015-08-15 08:37:26Z ale $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-gd

.include "${MASTERDIR}/Makefile"
