# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-System_Command/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	System_Command
PORTVERSION=	1.0.8
CATEGORIES=	devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR command line execution interface

USES=	pear

.include <bsd.port.mk>
