# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/net/p5-BBS-UserInfo/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	BBS-UserInfo
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:GSLIN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Base class of BBS::UserInfo::XXX

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
