# $FreeBSD: head/polish/libreoffice/Makefile 371023 2014-10-16 21:14:18Z jkim $

LO_I18N=	pl
LO_HAS_HELPPACK=	yes
CATEGORIES=	polish editors

.include "${.CURDIR}/../../editors/libreoffice/Makefile.common"

.include <bsd.port.mk>
