# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/www/pear-Services_W3C_HTMLValidator/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_W3C_HTMLValidator
PORTVERSION=	1.0.0
PORTEPOCH=	1
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Object Oriented Interface to the W3C HTML Validator service

BUILD_DEPENDS=	${PEARDIR}/HTTP/Request2.php:${PORTSDIR}/www/pear-HTTP_Request2
RUN_DEPENDS=	${PEARDIR}/HTTP/Request2.php:${PORTSDIR}/www/pear-HTTP_Request2

USES=		pear

.include <bsd.port.mk>
