# Created by: Mike Meyer
# $FreeBSD: head/www/py-beautifulsoup/Makefile 371112 2014-10-18 10:52:53Z rm $

PORTNAME=	beautifulsoup
PORTVERSION=	4.3.2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	beautifulsoup4-${PORTVERSION}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	HTML/XML Parser for Python

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
