# Created by: Sylvio Cesar <sylvio@FreeBSD.org>
# $FreeBSD: head/devel/pear-PEAR_PackageFileManager_Plugins/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	PEAR_PackageFileManager_Plugins
PORTVERSION=	1.0.2
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	The plugins for PEAR_PackageFileManager

BUILD_DEPENDS=	${PEARDIR}/XML/Serializer.php:${PORTSDIR}/devel/pear-XML_Serializer
RUN_DEPENDS=	${PEARDIR}/XML/Serializer.php:${PORTSDIR}/devel/pear-XML_Serializer

LICENSE=	BSD2CLAUSE

USES=	pear

.include <bsd.port.mk>
