# $FreeBSD: head/devel/cx_Freeze/Makefile 392491 2015-07-19 09:42:32Z araujo $

PORTNAME=	cx_Freeze
PORTVERSION=	4.3.3
CATEGORIES=	devel python
MASTER_SITES=	SF/cx-freeze/${PORTVERSION}

MAINTAINER=	araujo@FreeBSD.org
COMMENT=	The cx_Freeze is a set of utilities for freezing Python scripts

USE_GCC=	yes
USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
