# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/net/py-simplesoap/Makefile 386250 2015-05-13 19:01:32Z sunpoet $

PORTNAME=	simplesoap
PORTVERSION=	1.10
PORTREVISION=	1
CATEGORIES=	net www python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Python Simple SOAP Library

LICENSE=	LGPL3

USE_PYTHON=	autoplist distutils
USES=		python

GH_ACCOUNT=	py${PORTNAME}
GH_PROJECT=	py${PORTNAME}
USE_GITHUB=	yes

.include <bsd.port.mk>
