# $FreeBSD: head/news/husky-smapi/Makefile 365427 2014-08-19 22:10:13Z marino $

PORTNAME=	husky-smapi
CATEGORIES=	news mail

MAINTAINER=	osharoiko@gmail.com
COMMENT=	Husky FTN MSGAPI library

LIB_DEPENDS=    libhusky.so:${PORTSDIR}/news/husky-huskylib

USE_LDCONFIG=	yes

MASTERDIR=	${.CURDIR}/../husky
COMPONENT_SUBDIR=	smapi

.include <bsd.port.mk>
