# $FreeBSD: head/devel/py-collective.monkeypatcher/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	collective.monkeypatcher
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Applying monkey patches on startup using ZCML configuration

LICENSE=	ZPL21

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
