# $FreeBSD: head/print/indexinfo/Makefile 381716 2015-03-20 07:56:25Z bapt $

PORTNAME=	indexinfo
PORTVERSION=	0.2.3
CATEGORIES=	print ports-mgmt

MAINTAINER=	bapt@FreeBSD.org
COMMENT=	Utility to regenerate the GNU info page index

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GITHUB=	yes
GH_ACCOUNT=	bapt
INSTALL_TARGET=	install-strip
PLIST_FILES=	bin/indexinfo

.include <bsd.port.mk>
