# Created by: Benno Rice <benno@jeamland.net>
# $FreeBSD: head/textproc/py-zpt/Makefile 374183 2014-12-07 10:01:36Z mva $

PORTNAME=	zpt
PORTVERSION=	2.5
CATEGORIES=	textproc python
MASTER_SITES=	SF
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	ZopePageTemplates-${PORTVERSION}
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Zope-less version of Zope Page Templates

USES=		python
USE_PYTHON=	distutils autoplist
WRKSRC=		${WRKDIR}/ZopePageTemplates

.include <bsd.port.mk>
