# Created by: rpsfa@rit.edu
# $FreeBSD: head/devel/rubygem-require_all/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	require_all
PORTVERSION=	1.3.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Wonderfully simple way to load your code

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
