# Created by: Nikolay Dachev <freebsd@dachev.info>
# $FreeBSD: head/net/py-ipaddress/Makefile 394940 2015-08-21 12:03:25Z amdmi3 $

PORTNAME=	ipaddress
PORTVERSION=	1.0.6
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python 3.3's ipaddress for Python 2.6 and 2.7

LICENSE=	PSFL

USES=		python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
