# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: head/devel/liblcfg/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTNAME=	liblcfg
PORTVERSION=	0.2.2
PORTREVISION=	2
CATEGORIES=	devel
MASTER_SITES=	http://liblcfg.carnivore.it/files/

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Lightweight configuration file library written in C99

LICENSE=	GPLv2

USES=		libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
