# Created by: Michael Moll <kvedulv@kvedulv.de>
# $FreeBSD: head/textproc/rubygem-jekyll-gist/Makefile 394947 2015-08-21 12:05:01Z sunpoet $

PORTNAME=	jekyll-gist
PORTVERSION=	1.3.3
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Liquid tag for displaying GitHub Gists in Jekyll sites

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
