# $FreeBSD: head/www/py-plonetheme.sunburst/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	plonetheme.sunburst
PORTVERSION=	1.4.5
PORTREVISION=	1
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Default theme for Plone 4

LICENSE=	GPLv2

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
