# Created by: arved
# $FreeBSD: head/net-mgmt/p5-SNMP-Info/Makefile 390368 2015-06-23 12:08:15Z jadawin $

PORTNAME=	SNMP-Info
PORTVERSION=	3.28
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Perl5 module for gathering information from network devices

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libnetsnmp.so:${PORTSDIR}/net-mgmt/net-snmp

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
