# Created by: Gerrit Beine (<tux@pinguru.net>)
# $FreeBSD: head/graphics/pear-Image_Color/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Image_Color
PORTVERSION=	1.0.4
CATEGORIES=	graphics www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR::Image_Color manages and handles color data and conversions

USE_PHP=	gd
USES=	pear

.include <bsd.port.mk>
