# $FreeBSD: head/www/elixir-webassembly/Makefile 391241 2015-07-03 13:59:45Z olgeni $

PORTNAME=	webassembly
PORTVERSION=	0.5.1
DISTVERSIONPREFIX=	v
CATEGORIES=	www
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	DSL for creating HTML structure straight with Elixir blocks.

LICENSE=	BSD2CLAUSE

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	herenowcoder

.include <bsd.port.mk>
