# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/textproc/pear-File_Fortune/Makefile 369312 2014-09-26 09:17:25Z bapt $

PORTNAME=	File_Fortune
PORTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	textproc pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Interface for reading from and writing to fortune files

USES=	pear

.include <bsd.port.mk>
