# $FreeBSD: head/www/py-plone.app.locales/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	plone.app.locales
PORTVERSION=	4.3.2
PORTREVISION=	1
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Translation files for Plone

LICENSE=	GPLv2

USES=		python:2 zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
