# Created by: Yuri Pankov <yuri.pankov@gmail.com>
# $FreeBSD: head/textproc/libunibreak/Makefile 359620 2014-06-27 22:24:16Z amdmi3 $

PORTNAME=	libunibreak
PORTVERSION=	1.1
PORTREVISION=	2
PORTEPOCH=	1
CATEGORIES=	textproc
MASTER_SITES=	SF/vimgadgets/${PORTNAME}/${PORTVERSION}

MAINTAINER=	fluffy@FreeBSD.org
COMMENT=	Implementation of the line and word breaking algorithm for Unicode

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
USES=		pathfix libtool

.include <bsd.port.mk>
