# Created by: Dan Langille <dvl@FreeBSD.org>
# $FreeBSD: head/devel/py-anyconfig/Makefile 374479 2014-12-10 16:43:27Z dvl $

PORTNAME=	anyconfig
PORTVERSION=	0.0.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dvl@FreeBSD.org
COMMENT=	Generic access to configuration files in many formats

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
