# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: head/devel/py-fs/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	fs
PORTVERSION=	0.4.0
CATEGORIES=	devel python
MASTER_SITES=	GOOGLE_CODE
PROJECTHOST=	pyfilesystem
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	Python filesystem abstraction

LICENSE=	ISCL

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
