# Created by: Jaap Boender <jaapb@kerguelen.org>
# $FreeBSD: head/devel/ocaml-deriving-ocsigen/Makefile 385413 2015-05-04 15:46:51Z madpilot $

PORTNAME=	deriving-ocsigen
PORTVERSION=	0.3c
CATEGORIES=	devel www
MASTER_SITES=	http://ocsigen.org/download/
PKGNAMEPREFIX=	ocaml-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Function derivation library

USE_OCAML=		yes
USE_OCAML_FINDLIB=	yes
USE_OCAML_CAMLP4=	yes
USE_OCAMLFIND_PLIST=	yes
USE_OCAML_LDCONFIG=	yes

USES=		gmake

.include <bsd.port.mk>
