# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/devel/pear-Console_CommandLine/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Console_CommandLine
PORTVERSION=	1.2.0
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Full featured command line options and arguments parser

USES=	pear

.include <bsd.port.mk>
