# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: head/devel/pecl-msgpack/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	msgpack
PORTVERSION=	0.5.5
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz
DIST_SUBDIR=	PECL

MAINTAINER=	johnpupu@gmail.com
COMMENT=	Provides API for communicating with MessagePack serialization

LICENSE=	BSD3CLAUSE

USE_PHP=	session
USE_PHPEXT=	yes
USE_PHP_BUILD=	yes

.include <bsd.port.mk>
