# $FreeBSD: head/devel/pructl/Makefile 380400 2015-03-03 23:58:04Z rpaulo $

PORTNAME=	pructl
PORTVERSION=	0.2
CATEGORIES=	devel
MASTER_SITES=	https://bitbucket.org/rpaulo/pructl/get/

MAINTAINER=	rpaulo@FreeBSD.org
COMMENT=	Utilities to interface with PRUs

LICENSE=	BSD2CLAUSE

LIB_DEPENDS=	libpru.so:${PORTSDIR}/devel/libpru

USES=		cmake

WRKSRC=		${WRKDIR}/rpaulo-pructl-ef9fa544e6a3

.include <bsd.port.mk>
