# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: head/devel/pear-HTML_Common/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_Common
PORTVERSION=	1.2.5
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR::HTML_Common is a base class for other HTML classes

USES=	pear

.include <bsd.port.mk>
