# Created by: Jyun-Yan You <jyyou@cs.nctu.edu.tw>
# $FreeBSD: head/net/rubygem-net-ldap/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	net-ldap
PORTVERSION=	0.11
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Pure Ruby LDAP support library with most client features

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/License.rdoc

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
