# $FreeBSD: head/x11-drivers/xf86-video-ark/Makefile 374982 2014-12-19 23:03:54Z dumbbell $

PORTNAME=	xf86-video-ark
PORTVERSION=	0.7.5
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org ark display driver

XORG_CAT=	driver

.include <bsd.port.mk>
