# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: head/www/pear-Services_Blogging/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Services_Blogging
PORTVERSION=	0.2.4
CATEGORIES=	www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PHP interface to Blog

BUILD_DEPENDS=	${PEARDIR}/XML/RPC.php:${PORTSDIR}/net/pear-XML_RPC
RUN_DEPENDS=	${PEARDIR}/XML/RPC.php:${PORTSDIR}/net/pear-XML_RPC

USES=	pear

.include <bsd.port.mk>
