# Created by: aturetta@commit.it
# $FreeBSD: head/devel/p5-Module-Refresh/Makefile 375950 2015-01-01 16:11:25Z sunpoet $

PORTNAME=	Module-Refresh
PORTVERSION=	0.17
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lippe@FreeBSD.org
COMMENT=	Refresh %INC files when updated on disk

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Path-Class>=0:${PORTSDIR}/devel/p5-Path-Class

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
