# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/devel/pear-Pager/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Pager
PORTVERSION=	2.4.9
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR data paging class

USES=	pear

.include <bsd.port.mk>
