# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11/nvidia-driver-304/Makefile 374695 2014-12-14 09:51:10Z danfe $

DISTVERSION=	304.125
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-304

.include "${MASTERDIR}/Makefile"
