# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: head/net/pear-Net_URL_Mapper/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_URL_Mapper
PORTVERSION=	0.9.1
CATEGORIES=	net www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple and flexible way to build nice URLs for web applications

USES=	pear

.include <bsd.port.mk>
