# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: head/textproc/rubygem-redcarpet/Makefile 390392 2015-06-23 12:22:45Z sunpoet $

PORTNAME=	redcarpet
PORTVERSION=	3.3.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast, safe and extensible Markdown to (X)HTML parser

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/redcarpet

.include <bsd.port.mk>
