# Created by: Thierry Thomas (<thierry@FreeBSD.org>)
# $FreeBSD: head/devel/pear-XML_SVG/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	XML_SVG
PORTVERSION=	1.1.0
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR object-oriented API for building SVG documents

USES=	pear

.include <bsd.port.mk>
