# Created by: ijliao
# $FreeBSD: head/sysutils/and/Makefile 380691 2015-03-07 13:47:32Z wen $

PORTNAME=	and
PORTVERSION=	1.2.2
CATEGORIES=	sysutils
MASTER_SITES=	SF

MAINTAINER=	portmaster@BSDforge.com
COMMENT=	Auto Nice Daemon

USES=		gmake
ALL_TARGET=	default
NOPRECIOUSMAKEVARS=	yes

.include <bsd.port.mk>
