# Created by: mat
# $FreeBSD: head/devel/p5-Test-Cmd/Makefile 394305 2015-08-15 12:09:57Z sunpoet $

PORTNAME=	Test-Cmd
PORTVERSION=	1.08
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Portable testing of commands and scripts

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
