# $FreeBSD: head/databases/sqlrelay/Makefile.common 393725 2015-08-08 12:11:27Z pi $

SQLRELAY_PORTNAME=	sqlrelay
SQLRELAY_PORTVERSION=	0.62

SQLRELAY_PORTDIR=	${PORTSDIR}/databases/${SQLRELAY_PORTNAME}
SQLRELAY_WRKSRC_CMD=	cd ${SQLRELAY_PORTDIR} && ${MAKE} -V WRKSRC

SQLRELAY_CONFIGURE_ARGS=	\
		--localstatedir=/var \
		--with-rudiments-prefix="${LOCALBASE}"
