# Created by: mat
# $FreeBSD: head/devel/p5-Devel-PPPort/Makefile 381205 2015-03-13 14:02:22Z sunpoet $

PORTNAME=	Devel-PPPort
PORTVERSION=	3.31
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl/Pollution/Portability

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
