# Created by: Franz Klammer <klammer@webonaut.com>
# $FreeBSD: head/devel/pear-HTML_Template_Sigma/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTML_Template_Sigma
PORTVERSION=	1.3.0
CATEGORIES=	devel www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR template API

USE_PHP=	ctype
USES=	pear

.include <bsd.port.mk>
