# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11/randrproto/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	randrproto
PORTVERSION=	1.4.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Randr extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
