# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: head/databases/pear-DBA/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	DBA
PORTVERSION=	1.1.1
CATEGORIES=	databases www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Berkely-style database abstraction class

USES=		pear

.include <bsd.port.mk>
