# Created by: Daniel Walter <sahne@0x90.at>
# $FreeBSD: head/sysutils/bsdmoted/Makefile 367236 2014-09-03 21:07:17Z antoine $

PORTNAME=	bsdmoted
PORTVERSION=	0.4.0
CATEGORIES=	sysutils
MASTER_SITES=	SF

MAINTAINER=	sahne@0x90.at
COMMENT=	Use Wii remote as mouse

USES=		uidfix
PLIST_FILES=	sbin/bsdmoted

.include <bsd.port.mk>
