# $FreeBSD: head/www/py-plone.alterego/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	plone.alterego
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Low level support for dynamic modules

LICENSE=	LGPL20

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
