# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/science/R-cran-snow/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	snow
DISTVERSION=	0.3-13
PORTREVISION=	4
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Support for simple parallel computing in R

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	cran:auto-plist

.include <bsd.port.mk>
