# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: head/net/pear-Net_MAC/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_MAC
PORTVERSION=	0.1.5
PORTREVISION=	1
CATEGORIES=	net pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class that validates and formats MAC addresses

USES=	pear

.include <bsd.port.mk>
