# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/security/pear-Net_Portscan/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Net_Portscan
PORTVERSION=	1.0.3
CATEGORIES=	security pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Provides an API for scanning ports

USES=	pear

.include <bsd.port.mk>
