# $FreeBSD: head/textproc/rubygem-github-markup/Makefile 393415 2015-08-02 06:29:53Z sunpoet $

PORTNAME=	github-markup
PORTVERSION=	1.4.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Render any fancy markup

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/github-markup

.include <bsd.port.mk>
